### ISSUE TITLE
add_worker() got an unexpected keyword argument 'cpu'

### ISSUE THREAD

**Issue by jhamman** [dask/dask-kubernetes#102]
Just testing dask-kubernetes with current versions of dask and distributed. I'm seeing some discrepancies in the `add_worker` method. 

```Python-traceback
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'cpu'
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.6/site-packages/distributed/core.py", line 340, in handle_comm
    result = yield result
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'cpu'
```
https://circleci.com/gh/dask/dask-kubernetes/154?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mrocklin** [comment]
I suspect that the workers are using an older version of dask-distributed.
Maybe you need to also update the worker image used in testing?

**Comment by jhamman** [comment]
Would that be `daskdev/dask:latest`?

**Comment by mrocklin** [comment]
Try daskdev/dask:0.19.2 (just pushed)

**Comment by mrocklin** [comment]
Again, trying to keep versions explicit here (which should also help to
avoid confusion when latest in conda and docker grow out of sync

**Comment by jhamman** [comment]
I'm actually not sure where the worker-image is specified for the tests. 

BTW, I totally see why we need to pin versions in this case.

**Comment by mrocklin** [comment]
```
mrocklin@carbon:~/workspace/dask-kubernetes$ git grep daskdev
.circleci/config.yml:            /home/circleci/miniconda/envs/dask-kubernetes-test/bin/py.test dask_kubernetes -s --verbose --worker-image daskdev/dask:0.17.4.2018-05-18
```

We should modify the tag afer daskdev/dask to match 0.19.2

**Comment by jhamman** [comment]
Thanks @mrocklin - that get's me closer.
