### ISSUE TITLE
Proxy for worker and scheduler dashboards

### ISSUE THREAD

**Issue by athornton** [dask/dask-kubernetes#107]
One slightly tricky bit with running dask in a kubernetes environment (we're doing JupyterHub + JupyterLab + k8s) is that the dashboards are all on the internal, private network, and there's only the one https endpoint that leads you to the hub and then proxies you to your container.

If you want to use bokeh inside JupyterLab in this sort of environment, you end up using nbserverproxy anyway to map local ports to a route mapped into your https endpoint.

Turns out you can do a similar trick for the scheduler proxy.  This is how we do it at LSST, and I think with a little work we could drop the LSST-specific environmental bits and make it a generic part of dask-kubernetes:

https://github.com/lsst-sqre/jupyterlabutils/blob/master/jupyterlabutils/notebook/lsstdaskclient.py

All that does is to replace the representation of the scheduler dashboard endpoint with its equivalent mapped through the hub user proxy and the nbserver proxy.

The other piece is a little more interesting.  What this does is to collect the worker status dashboard URLs, create local-to-the-scheduler-and-therefore-notebook TCP proxies to the worker host/bokeh-port, hook those into the existing IOLoop, and then return the proxy addresses pointing to those ports to the user.  That lets you hit the worker dashboards from your browser, despite the fact that everything is running on the k8s private notebook:

https://github.com/lsst-sqre/jupyterlabutils/blob/master/jupyterlabutils/notebook/clusterproxy.py

Both of these in their current form depend on environment variables I'm injecting as part of the LSST Lab setup; I'd like to discuss how we can make them generic and roll them into dask-kubernetes.

**Comment by jacobtomlinson** [comment]
Sorry that nobody responded to this issue.

I imagine much of this has been superseded with the [dask labextension](https://github.com/dask/dask-labextension). You can also access worker dashboards via the scheduler dashboard using the same techniques.

I'm going to close this as out of date, but if I've gotten the wrong end of the stick please don't hesitate to ask for it to be reopened.

**Comment by athornton** [comment]
Is there a native way to tell the labextension to point at a scheduler that's behind a single HTTPS endpoint?  I know there was talk of something that depends on a change to jupyter-server-proxy but I don't know if that ever got merged.

**Comment by jacobtomlinson** [comment]
I'm not sure if I understand the question. You can currently provide the extension with the URL of the dashboard, or it will attempt to autodetect it from the cluster object.

**Comment by athornton** [comment]
Ohhhh...yeah, I need to try feeding the internal URL to the dashboard connection widget.  The way I've been doing it, via jupyter-server-proxy works, but it's probably not necessary now that the lab extension exists.  I had forgotten that I created the proxy (and the worker scheduler proxies) as a way to get a new _browser_ tab open pointing at the dashboard initially.
