### ISSUE TITLE
Use black on this codebase?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#120]
I would like us to use the black code formatter on this codebase, and set it up in pre-commit hooks, and CI.  Any objections?

**Comment by ian-r-rose** [comment]
No objections, I like it as well

**Comment by jacobtomlinson** [comment]
Happy with this!

**Comment by mrocklin** [comment]
I'll do this after the async changes.

**Comment by jcrist** [comment]
Fixed by #153.
