### ISSUE TITLE
Update Helm chart in stable/dask

### ISSUE THREAD

**Issue by beberg** [dask/dask-kubernetes#128]
The Helm chart published in stable/dask and the documentation needs some updates. Taking this opportunity to do a full update and review.

- Update API versions
- Refactor NOTES.txt to handle LoadBalancer, NodePort, and ClusterIP. Model after wordpress NOTES.txt.
- Add OWNERS file (danielfrg, mrocklin, beberg) and Chart.yaml maintainers:
- Add comments into values.yaml for NodePort, ClusterIP, and GPU settings.
- README needs to explain when to use each type, and the additional YALM via -f , or directly with --set flags to pass in. Update rest of README.
- Lint yaml and .md where possible (VSCode davidanson.vscode-markdownlint and redhat.vscode-yaml extensions are good)
- Document the Jupyter password in the README and how to change it. (we can address securing the ports next time)
- Update to v1.1.1 containers
- Add namespace, imagePullSecrets, and nodeSelector support.
- Support alternative dask-worker.

Work is being done by @rmccorm4 and draft PR is at https://github.com/rmccorm4/charts/pull/1 for review.

**Comment by jacobtomlinson** [comment]
Awesome stuff! I would appreciate being added to the OWNERS file too.

However I'm afraid this repo is for a python library for creating ad hoc dask cluster on kubernetes and is not related to that chart. It might be more appropriate to open this issue on the helm/charts repo and cc relevant maintainers.

Also I noticed that PR you referenced is not comparing against the upstream charts repo, but against the master branch in the fork. Is this intentional?

**Comment by beberg** [comment]
Issue is opened here since dask/helm-chart is deprecated, so discuss among Dask folks before putting a clean PR up to helm repo. Working in user's branch is intentional.

@zonca @cpanato @mrocklin

**Comment by jacobtomlinson** [comment]
I would like to propose that we fork helm/charts to dask/charts (or maybe dask/helmcharts or similar) and treat that as the official place to raise issues like this, have discussions and iterate on the chart. Then we can raise PRs against helm/charts from there.

What are your thoughts @beberg @mrocklin ?

**Comment by mrocklin** [comment]
No strong thoughts from me

**Comment by beberg** [comment]
The alternative is to resurrect dask/helm-chart but that would create two sources of truth for the chart, which I would oppose, there should be only one. May even want to remove dask/helm-chart to avoid any possible user confusion, or at least make it very clear it's archived.

This PR was quite large and there is no OWNERS file yet, so it's a bit of a one time thing. helm/charts should be the definitive source, and future PRs should go there once we have the OWNERS file. 

Added jacobtomlinson to chart OWNERS.
