### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jcrist** [dask/dask-kubernetes#139]
Since the new kubernetes release breaks this library (fixed in #136), we may want to issue a release.

**Comment by jhamman** [comment]
I'll echo this request. #142 and #143 both seem ready to merge. Any chance we can get a new release in the next few days? I'm happy to help push things along.

**Comment by mrocklin** [comment]
I'd be quite happy to enable either of you to do this if you're interested (I'd like to stop being the bottleneck on releases of all Dask subprojects).  What are your PyPI handles?  Are people comfortable with the process in https://github.com/dask/dask/blob/master/docs/release-procedure.md ?

**Comment by jhamman** [comment]
@mrocklin - happy to run through the release procedure. PyPI handle is jhamman.

**Comment by mrocklin** [comment]
After checking with @jcrist (as per our commit right policy) @jhamman you now have commit rights here and on PyPI for this repository.

**Comment by jhamman** [comment]
Thanks @mrocklin!

**Comment by mrocklin** [comment]
We might want to sneak in #149

**Comment by jhamman** [comment]
Is this release going to be 0.8. For reference, the diff from the last tag is here: https://github.com/dask/dask-kubernetes/compare/0.7.0...master

**Comment by mrocklin** [comment]
0.8 sounds good to me

**Comment by jhamman** [comment]
Okay, I'll make this release later today.

**Comment by jhamman** [comment]
closed by ebe0ed24b5c896062008eb276577a8b25a9ee501. 

The 0.8.0 release is up on pypi. It should make it to conda-forge here soon.
