### ISSUE TITLE
Add docs for GPU deployment

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#144]
Should we include a small section informing users how to request containers with GPUs?  My gut reaction to this is "yes", but I'm also in a biased situation.  Ideally I'd like for some non-NVIDIA affiliated person to sign off on this.  

Looking at you @yuvipanda :)

**Comment by yuvipanda** [comment]
yes! I haven't used it personally, but let's do it!

**Comment by beberg** [comment]
I should finish the docs that go along with the cuda-worker and Helm chart changes... I'll try and do that in the next few days.
