### ISSUE TITLE
Summary of async status

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#157]
We would like for dask-kubernetes to support async operation for a few reasons:

1.  It will allow it to be used more effectively within dask-labextension
2.  It would allow users to use it within async applications
3.  Most resource managers should probably support this medium-term for consistency

We have a few options here:

1.  Swap out `kubernetes` with `kubernetes_asyncio` everywhere and await things as necessary.  This is done in the `dev` branch, but there are a few failures.   https://github.com/dask/dask-kubernetes/pull/138 https://github.com/dask/dask-kubernetes/pull/132
2.  Rewrite things from scratch:  The current implementation is alright, but definitely grew organically.  A full rewrite may be easier given the rather small scope of the problem.
3.   Rewrite with `SpecCluster`:  The [SpecCluster](https://github.com/dask/distributed/blob/master/distributed/deploy/spec.py) class in dask.distributed provides much of the boiler-plate around dask and starting/stopping workers asynchronously.  To use this we would need to make a class that looked like `dask.distributed.Worker` or `dask.distributed.Nanny`, but that actually created a Pod in Kubernetes.  This is very similar to how Nanny works, but replaces a process with a pod.

Who can do this work?

There are a few people around who have both interest and ability here.  @quasiben @TomAugspurger @jacobtomlinson and myself.  It's also possible that if we're able to strip away the Dask-specific stuff (which may be hard) that we can get some other Kubernetes person from within NVidia to help.  I *think* that the SpecCluster approach comes close to this.

**Comment by ian-r-rose** [comment]
It may be worthwhile to back off of expecting an asynchronous cluster in `dask-labextension` while this is resolved. We clearly got a bit ahead of ourselves there :)

The main consequence of that would be (if memory serves), slower startup time for launching a server with initial clusters, since they can't be pushed onto the event loop.

**Comment by jacobtomlinson** [comment]
I'm starting to look at this in #162. 

I'm aiming to tick all three of the options off the list. Switch to async kubernetes and make use of `SpecCluster`, which will be such a big overhaul I may as well do some more major refactoring here. It'll probably look like a rewrite once I'm done.

**Comment by jacobtomlinson** [comment]
Closed in #162.
