### ISSUE TITLE
Version number for next release

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#167]
Hi All, 

As part of an upcoming release I would like to release dask-jobqueue.  What should the version number be?  Some options:

1.  `0.9.1` - this will be a minor version change in functionality
2.  `1.0` - this library is fairly stable, might as well call it `1.0`
3.  `2.2` - let's just match Dask version numbers going forward

What should we use?

**Comment by mrocklin** [comment]
I've released version 0.9.1.  I'm going to leave this open though, I think that we should consider a large version number change if #162 gets merged.

**Comment by jacobtomlinson** [comment]
Agree that separate versioning makes sense here and that moving to `SpecCluster` is a good point to go `1.0`. 

Although given that it will be a substantial rewrite stability is likely to go down temporarily as new bugs are found. So maybe some pre releases would be good?

**Comment by jacobtomlinson** [comment]
In #184 @jhamman has proposed `0.10.0`. Does anyone have any more input here?
