### ISSUE TITLE
KubeCluster constructor should call the constructor of Cluster

### ISSUE THREAD

**Issue by heavenmarshal** [dask/dask-kubernetes#178]
From dask.distributed 2.3.0, the distributed.deploy.Cluster added a constructor. However the constructor of the derived class KubeCluster does not call the constructor of the base class. It may lead to the following exception

Exception ignored in: <bound method Cluster._del_ of KubeCluster("tcp://10.38.1.93:43414", workers=8)>
Traceback (most recent call last):
File "/usr/local/envs/SelfHealing/lib/python3.6/site-packages/distributed/deploy/cluster.py", line 86, in _del_
if self.status != "closed":
AttributeError: 'KubeCluster' object has no attribute 'status'

**Comment by heavenmarshal** [comment]
Sorry, I failed to produce it in a small example. It seems that my work flow finishes normally since the exception is ignored. But this exception shows up at the end of the log. I am not sure whether this version (dask-kubernetes=0.9.2) is safely compatible with distributed>=2.3.0.

**Comment by jacobtomlinson** [comment]
I'm afraid without an example we can't really explore this further. 

As the error is related to cleanup I would check your kubernetes cluster to ensure there are no stray pods left there.
