### ISSUE TITLE
Querying the system monitor on dask-kubernetes workers? 

### ISSUE THREAD

**Issue by limx0** [dask/dask-kubernetes#180]
A nice feature of the LocalCluster is the ability to query the workers resources via 

```python
cluster = LocalCluster()
resources = {w: w.monitor.range_query(0) for w in cluster.workers}
```

Does the same exist for the workers started with dask_kubernetes? I can't seem to find anything in the code, but @mrocklin suggested that all workers run the monitor internally.

**Comment by jacobtomlinson** [comment]
I'm afraid this isn't possible from dask-kubernetes as the worker objects exist remotely and it is not possible to access these attributes.

@mrocklin is there a way we could support this over the dask comm?

**Comment by mrocklin** [comment]
The easiest thing to do today would be to use `Client.run`

```python
def f(dask_worker):
    return dask_worker.monitor.range_query(0)

resources = client.run(f)
```

**Comment by limx0** [comment]
Perfect, thank you @mrocklin!
