### ISSUE TITLE
Annotation Support in `make_pod_spec`

### ISSUE THREAD

**Issue by fritz-clicktripz** [dask/dask-kubernetes#183]
As a developer - I'd like to be able to use the `make_pod_spec` function and provide annotations for my dask worker pods. This is particularly helpful when I want to use generally the defaults, but need something like an IAM role supplied with kube2iam in AWS.

**Comment by jacobtomlinson** [comment]
Sure that sounds reasonable!

This would involve adding a [new kwarg here](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/objects.py#L102) similar to the labels one, and then passing that through to the [metadata spec here](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/objects.py#L130).

Is this something you would be interested in contributing @fritz-clicktripz?

**Comment by fritz-clicktripz** [comment]
@jacobtomlinson Sure! No ETA on when, but it doesn't look too intimidating. I don't see a contribution guide - is there anywhere I can look or anyone I can directly message if I have any problem running unit tests or etc?

**Comment by jacobtomlinson** [comment]
Good point. We should probably have a contributing doc file which points folks [here](https://docs.dask.org/en/latest/develop.html#contributing-to-code).

You can ask questions in the [dev channel on Gitter](https://gitter.im/dask/dev).
