### ISSUE TITLE
Connect to existing running cluster

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#185]
It would be great to be able to attach a `KubeCluster` instance to an already running Dask cluster. This could be a cluster created with the [Dask helm chart](https://github.com/helm/charts/tree/master/stable/dask) for example.

We could then be able to take over scaling duties locally in our `KubeCluster` object and generally be able to interact with the cluster from our Python session.

**Comment by raybellwaves** [comment]
I would be interested in working on this. I will need some hand-holding though.

**Comment by jacobtomlinson** [comment]
Thanks @raybellwaves.

The main challenges here are going to be that the two approaches handle scaling different.y

In dask-kubernetes we are manually creating pods. However the Helm Chart uses a deployment to create them. There are pros and cons to each approach.

To support things here we would need to detect which mode of cluster we are connecting to and change our scaling technique accordingly.

**Comment by griseau** [comment]
Hi guys, 

Do you have any update on this ? Or do you have any other solution to run the scheduler in kubernetes and be able to adapt the number of pods ? As far as I know, not possible today using helm deployment 

Thanks

**Comment by jacobtomlinson** [comment]
This has been implemented in the operator in #460 and we have no plans to implement this in the classic `KubeCluster`. 

If you need this functionality I recommend switching to the [operator](https://kubernetes.dask.org/en/latest/operator.html).
