### ISSUE TITLE
Detach from running cluster

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#186]
The current behaviour of dask-kubernetes is to create ephemeral clusters and use them to perform calculation. There is a bunch of logic here to clean up the cluster when the Python object is removed.

This may not always be the desired use case and we may want to support detaching from a cluster. This also fits with #185 where we may want to attach to an already running cluster.

**Comment by mrocklin** [comment]
I think that @jcrist has conventions for this in dask-gateway and
dask-yarn.

**Comment by jcrist** [comment]
We use the keyword `shutdown_on_close` in dask-gateway (defaults to True, except when connecting to a running cluster then the default is False). Typically a `cluster` object has a few things you'd want to cleanup:

- Remote cluster resources (e.g. kubernetes pods)
- Local async things (event loop, background tasks, comms, etc...)

The `.close()` method is always called on GC of an object, but the meaning of `.close()` differs based on the value of `shutdown_on_close` for the cluster.

```python
# On .close()/GC of cluster object, remote cluster is cleaned up
cluster = GatewayCluster()
cluster.close()

# On .close()/GC of cluster object, only local resources are cleaned up
cluster = GatewayCluster(shutdown_on_close=False)
cluster.close()

# You can override this behavior by passing `shutdown=True` to close
# or using the `shutdown()` method which is an alias to this
cluster.close(shutdown=True)
cluster.shutdown()
```

This option only makes sense if the scheduler is remote (which is always true for dask-gateway).

**Comment by jacobtomlinson** [comment]
Thanks @jcrist this is the kind of thing I want to implement here. Now that we have the option of [creating remote schedulers](https://github.com/dask/dask-kubernetes/issues/84#issuecomment-541601780) it would be good to implement this functionality.

**Comment by jacobtomlinson** [comment]
I'm going to close this out as being closely related to #185.
