### ISSUE TITLE
Run KubeCluster in a separate pod

### ISSUE THREAD

**Issue by hhuuggoo** [dask/dask-kubernetes#204]
Hi, at [Saturn Cloud](https://www.saturncloud.io), we're looking into running `KubeCluster` in a separate pod - the primary reason being that we don't want users Jupyter instances to have priveleges for spinning up pods directly.  

Is this work interesting to anyone else?  If so let me know!  would like to collaborate with folks.

We are using #84 - this is specifically about also moving the KubeCluster part (which creates more worker pods based on load) into it's own pod as well)

**Comment by jacobtomlinson** [comment]
Have you seen the kubernetes support in [Dask gateway](https://gateway.dask.org/)? I think that may tick the boxes you're looking at.

**Comment by hhuuggoo** [comment]
@jacobtomlinson interesting - it looks like this doesn't use `dask_kubernetes` at all.  Is this the new direction?  Or are both projects going to be used (but for different purposes)

**Comment by jacobtomlinson** [comment]
> Or are both projects going to be used (but for different purposes)

This. The different projects have been built differently as they have different requirements.

I'm definitely keen to unite things where possible. But am aware that if we try and make a central codebase which meets both sets of requirements we may end up making things overly complex.

**Comment by hhuuggoo** [comment]
Thank you.  I'll have a look at understanding out dask-gateway works.
