### ISSUE TITLE
scheduler closing with deploy_mode='remote'

### ISSUE THREAD

**Issue by bolliger32** [dask/dask-kubernetes#206]
Using `KubeCluster(deploy_mode='remote')`, the `scheduler_timeout` kwarg seems to define the amount of time following any active requests from the client before which the scheduler closes.

For example, if I call:
```
cluster = KubeCluster(deploy_mode='remote', scheduler_timeout='10s')
client = Client(cluster)
future = client.submit(some_function,some_args)
```

The scheduler will close (and the client will close) 10s after that call to `submit`. If I keep making calls to `submit`, however, then the scheduler and client will keep staying alive.

If I understand this kwarg correctly, it should not have this behavior (and, indeed it doesn't with a LocalCluster). My expected behavior is that unless the client dies (e.g. from restarting the python kernel), it would still be connected to the scheduler and this timeout should not trigger.

**Comment by jacobtomlinson** [comment]
That is also my understanding. This feature is actually part of the scheduler in distributed and only passed through from here. I'll copy your issue over there and reference it back to here.

**Comment by bolliger32** [comment]
Thanks!

**Comment by bolliger32** [comment]
just noting that dask/distributed#3265 points out that this is not necessarily on issue in distributed but rather dask-kubernetes may be invoking an inappropriate flag when `scheduler_timeout` is set. It is using this value for `idle_timeout` which intentionally has the observed behavior. I don't actually need `idle_timeout` OR the functionality that was supposed to be invoked by `scheduler_timeout` (timing out if a client wasn't connected to the scheduler for X amount of time). But it seems like its worth allowing `idle_timeout` (since it would just involve changing the kwarg name from `scheduler_timeout`. The other question is whether the originally intended functionality is useful. It probably is, in case you end up with a stranded scheduler?

**Comment by bolliger32** [comment]
One thing about `idle-timeout` - It was killing the scheduler but the pod was still alive. If the scheduler dies, I'm guessing it's probably good to delete the pod as well?
