### ISSUE TITLE
Configure scheduler pod separately from worker pods

### ISSUE THREAD

**Issue by Timost** [dask/dask-kubernetes#208]
Hi,
First of all thank you for working on dask integration with kubernetes !

I have a need that I think I can't fulfil at the moment with dask-kubernetes. My use case is the following:

I want to save money by using "pre-emptible" nodes (or low-priority in azure) for my worker pods.
However since these nodes can be shot at any time I want to put the scheduler pod on another node pool which is guaranteed to be stable, this can easily be achieved in kubernetes with taints/tolerations/affinities and I've been able to do it by working with kubernetes deployments directly. Using dask-kubernetes would be nice though because I could potentially have auto-scaling from dask directly and also easily submit jobs from dev computers (with dynamic dependencies) etc...

However, looking at the code, it seems I can't pass one deployment definition (aka `pod_template`) for the scheduler and another one for the worker pods.

Could you confirm this is not possible yet ? I'm willing to spend some time to implement this if you consider this is important/needed. Maybe adding an optional `scheduler_template` arg to the `KubeCluster` constructor, although there are already a lot of arguments...

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

You're right that both the scheduler and worker share a pod template. The fact that the scheduler runs as a pod at all is pretty new (by default it runs in the Python session that you are calling `dask-kubernetes` from). 

I agree that this would be good functionality to have, and if you wish to contribute it then I look forward to reviewing it.

**Comment by Timost** [comment]
Yes I saw the various issues: #84 #85 #111 
Ok I'll try implementing something then.
