### ISSUE TITLE
Cluster's `worker_spec` not updated when a worker pod is killed

### ISSUE THREAD

**Issue by ig248** [dask/dask-kubernetes#216]
Killing a worker pod (e.g. using `kubectl delete pod`) does not update the internal state of the cluster. Thus, (auto-)scaling behaviour gets out of sync.

This issue is likely to occur during a host node failure etc.

**Comment by ig248** [comment]
This appears to be a deeper problem with `ProcessInterface` not providing an interface for a liveliness probe, and `SpecCluster.workers` holding on to potentially dead worker instances. Any thoughts much appreciated!

**Comment by jacobtomlinson** [comment]
Looks like this was explored upstream in dask/distributed#2968. 

My understanding from that issue is that we need to implement a `_update_worker_status` method in the `KubeCluster` class which will be used to periodically check which workers are alive.

@mrocklin @guillaumeeb could you confirm this?

**Comment by ig248** [comment]
@jacobtomlinson Thank you, it looks doable, though in the meantime I have created an alternative solution that makes use of k8s-native `Deployment`: https://github.com/octoenergy/dask-remote/pull/1

**Comment by ig248** [comment]
@jacobtomlinson looking at `SpecCluster._update_worker_status()`, it appears that lost worker removal should be correctly inherited by `KubeCluster` - I may need to do additional testing.

**Comment by jacobtomlinson** [comment]
@ig248 thanks for the info. For more information on why we don't use `Deployment` resources see https://github.com/dask/dask-kubernetes/issues/168#issuecomment-518587280.
