### ISSUE TITLE
Pod name generation fails on some images

### ISSUE THREAD

**Issue by ig248** [dask/dask-kubernetes#218]
Pod name generation relies on `getpass.getuser()`. As per [documentation](https://docs.python.org/3.7/library/getpass.html#getpass.getuser), 
`getpass.getuser()` checks env for `LOGNAME`, `USER`, `LNAME` and `USERNAME`. As a matter of fact, [`daskdev/dask:latest`](https://hub.docker.com/layers/daskdev/dask/latest/images/sha256-2ac5385ebc20fe2982a22f8fcf3cf765e7a01dc5e5003b42aa44493af0a06438) does not set these.

**Comment by jacobtomlinson** [comment]
There are likely many assumptions along these lines. This library is often used with [zero-to-jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) which does set these are part of the scheduling.

Would be great to fix this with some more sensible default.

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
