### ISSUE TITLE
Errors in coroutines on closing a `KubeCluster` that was never entered/started

### ISSUE THREAD

**Issue by ig248** [dask/dask-kubernetes#220]
## Steps to reproduce
```
PYTHONASYNCIODEBUG=1 python -c "from dask_kubernetes import KubeCluster; KubeCluster()"
```
shows a number of errors.

## Update - fairly low priority in retrospect
this is due to no `pod_template` being provided. The error handling is happening in a coroutine - should it be made to fail synchronously for easier debugging?

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
