### ISSUE TITLE
External-Ip status always <pending>

### ISSUE THREAD

**Issue by diogocaribe** [dask/dask-kubernetes#224]
I've installed dask-kubernets (I am naive in dask and kubernets. I'm learning both) however the external-ip not working. What can I do to expose IP for this services?

![image](https://user-images.githubusercontent.com/7991205/72928113-28c8d480-3d36-11ea-9f61-add051e8a594.png)

**Comment by Kyrremann** [comment]
You need an internal load balancer to get a external IP, way out of scope for Dask.

**Comment by jacobtomlinson** [comment]
@Kyrremann is correct that you do not appear to have your kubernetes cluster configured to fulfil the load balancers and so they will stay in pending forever.

If you provide some more information on how you created your kubernetes cluster I can point you in the right direction.

**Comment by zengzhengrong** [comment]
Yor can access use NodePort service or install metallb to get the external IP

**Comment by jacobtomlinson** [comment]
Closing with no response.
