### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by lukejpreston** [dask/dask-kubernetes#226]
Could we get a release with the fix from #198, please?

**Comment by jacobtomlinson** [comment]
I'll aim to get this done this week.

**Comment by jakirkham** [comment]
Thanks Jacob! 😄

**Comment by jacobtomlinson** [comment]
Pushed 0.10.1 to PyPI, Conda Forge robots should raise PR soon.

**Comment by jacobtomlinson** [comment]
Now on conda forge

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson!
