### ISSUE TITLE
Adaptive Scaling on GKE

### ISSUE THREAD

**Issue by manujchandra** [dask/dask-kubernetes#235]
Hi,

I am trying to use dask-kubernetes but I have no luck so far. I have a working setup cluster using the helm method. But I have to manually scale it up. I have a pod with jupyter, one with the scheduler in GKE as installed by helm. Now, I want to implement adaptive scaling.

When I do this: 
```
cluster = KubeCluster.from_yaml('worker-spec.yml', host='104.155.143.150')
```

104.155.143.150 is where help setup my scheduler.

I get the error `OSError: [Errno 99] Cannot assign requested address`

Otherwise, I am able to access the public IPs of the pods and work with them.

My question is this:

1) Can dask-kubernetes be used in GKE to adaptive scale an installation extending from the helm method?
2) Can dask-kubernetes be only used with Pangeo Binder? 
3) If it's possible to use it on GKE, are there any resources available to learn the same?

What I am trying to do is to implement adaptive scaling on GKE. Thanks for the help!

---------------------------------------------------------------------------

```
distributed.scheduler - INFO - Clear task state


OSError                                   Traceback (most recent call last)
<ipython-input-6-534e1779dd38> in <module>
----> 1 cluster = KubeCluster.from_yaml('worker-spec.yml', host='104.155.143.150')

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in from_yaml(cls, yaml_path, **kwargs)
    638             d = yaml.safe_load(f)
    639             d = dask.config.expand_environment_variables(d)
--> 640             return cls.from_dict(d, **kwargs)
    641 
    642     @property

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in from_dict(cls, pod_spec, **kwargs)
    600         KubeCluster.from_yaml
    601         """
--> 602         return cls(make_pod_from_dict(pod_spec), **kwargs)
    603 
    604     @classmethod

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, auth, idle_timeout, deploy_mode, interface, protocol, dashboard_address, security, scheduler_service_wait_timeout, scheduler_pod_template, **kwargs)
    414         self.auth = auth
    415         self.kwargs = kwargs
--> 416         super().__init__(**self.kwargs)
    417 
    418     def _get_pod_template(self, pod_template, pod_type):

/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    255         if not self.asynchronous:
    256             self._loop_runner.start()
--> 257             self.sync(self._start)
    258             self.sync(self._correct_state)
    259 

/opt/conda/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    158             return future
    159         else:
--> 160             return sync(self.loop, func, *args, **kwargs)
    161 
    162     async def _logs(self, scheduler=True, workers=True):

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     if error[0]:
    344         typ, exc, tb = error[0]
--> 345         raise exc.with_traceback(tb)
    346     else:
    347         return result[0]

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in f()
    327             if callback_timeout is not None:
    328                 future = asyncio.wait_for(future, callback_timeout)
--> 329             result[0] = yield future
    330         except Exception as exc:
    331             error[0] = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in _start(self)
    572         self.worker_spec = {i: self.new_spec for i in range(self._n_workers)}
    573 
--> 574         await super()._start()
    575 
    576     @classmethod

/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py in _start(self)
    283 
    284         self.status = "starting"
--> 285         self.scheduler = await self.scheduler
    286         self.scheduler_comm = rpc(
    287             getattr(self.scheduler, "external_address", None) or self.scheduler.address,

/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py in start(self)
   1403         if self.status != "running":
   1404             for addr in self._start_address:
-> 1405                 await self.listen(addr, listen_args=self.listen_args)
   1406                 self.ip = get_address_host(self.listen_address)
   1407                 listen_ip = self.ip

/opt/conda/lib/python3.7/site-packages/distributed/core.py in listen(self, port_or_addr, listen_args)
    319             connection_args=listen_args,
    320         )
--> 321         await listener.start()
    322         self.listeners.append(listener)
    323 

/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py in start(self)
    409                 # is large enough not to lose any.
    410                 sockets = netutil.bind_sockets(
--> 411                     self.port, address=self.ip, backlog=backlog
    412                 )
    413             except EnvironmentError as e:

/opt/conda/lib/python3.7/site-packages/tornado/netutil.py in bind_sockets(port, address, family, backlog, flags, reuse_port)
    172 
    173         sock.setblocking(False)
--> 174         sock.bind(sockaddr)
    175         bound_port = sock.getsockname()[1]
    176         sock.listen(backlog)

OSError: [Errno 99] Cannot assign requested address
```

**Comment by jacobtomlinson** [comment]
> I have a working setup cluster using the helm method.

The helm chart and the `dask-kuberenetes` project are separate things. If you are using the helm chart please raise an issue [over there](https://github.com/dask/helm-chart).

To answer your questions:

> Can dask-kubernetes be used in GKE to adaptive scale an installation extending from the helm method?

Not currently. These are two separate projects. The helm chart allows you to create a static cluster which is scaled manually. `dask-kubernetes` allows you to create ephemeral clusters which only exist for the duration of your Python session, these do support autoscaling.

> Can dask-kubernetes be only used with Pangeo Binder?

`dask-kubernetes` can be used with any Kubernetes cluster, hower the primary use case for it is within Jupyter Hub and Binder.

https://zero-to-jupyterhub.readthedocs.io/en/latest/

> If it's possible to use it on GKE, are there any resources available to learn the same?

I'm not sure I understand this question.

**Comment by manujchandra** [comment]
@jacobtomlinson Hi!

Thanks a lot for clarifying my doubts. I have a much clear picture now. Please allow me to clarify my last question, and what I wish to do:

I want to replicate the [following](https://www.youtube.com/watch?v=dViyEqOMA8U&t=2s) using GKE (Google Kubernetes Engine).

Is there any resource that can show me how to set up a dynamic cluster just like in the video, but on the GKE?

It should have Jupyterlab with Dask Extention, `dask-kubernetes` and I should be able to scale it up and down dynamically. 

Thanks a lot!

P.S: I did manage to load the [dask notebook](https://github.com/dask/dask-docker/tree/master/notebook) on GKE as a pod. Exposed the pod. When I connect to it using the public IP, nothing happens. I was hoping for the Jupyterlab to open.

**Comment by jacobtomlinson** [comment]
Sure. That video is using [Zero 2 JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html) to provide the notebook environment and then [dask-kubernetes](https://kubernetes.dask.org/en/latest/) to provide the cluster.

Much of this work in terms of cluster building (overall cluster rather than just Dask cluster) was done as part of the Pangeo community. You may wish to check out [their helm chart](https://github.com/pangeo-data/helm-chart) which will give you all of the things described above.

**Comment by jacobtomlinson** [comment]
> P.S: I did manage to load the dask notebook on GKE as a pod. Exposed the pod. When I connect to it using the public IP, nothing happens. I was hoping for the Jupyterlab to open.

This would be my expectation so there must be some issue with the configuration.
