### ISSUE TITLE
add conda forge install instructions

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-kubernetes#240]
add conda forge install instructions here https://kubernetes.dask.org/en/latest/#install (https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#install).

Could copy from dask-jobqueue https://jobqueue.dask.org/en/latest/install.html#installing

**Comment by jrbourbeau** [comment]
Adding `conda` install instructions would be a nice addition to the docs. Any interest in submitting a PR? (no obligation though)

**Comment by raybellwaves** [comment]
Sure

**Comment by raybellwaves** [comment]
Hope you don't mind me expanding this a little I will add something along the lines of `conda install -c conda-forge dask-kubernetes dask` to have the packages material to run the example
