### ISSUE TITLE
doc hyperlinlink to KubeCluster 

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-kubernetes#241]
In https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#best-practices under 1. It says 'See KubeCluster docstring below for guidance on how to check and modify this.'. I believe there is a way to hyperlink it to https://kubernetes.dask.org/en/latest/api.html#dask_kubernetes.KubeCluster

**Comment by TomAugspurger** [comment]
Closed by #243.
