### ISSUE TITLE
further documentation on KubeCluster name

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-kubernetes#242]
I came across an issue here as my mac username is Ray (capital R).

https://stackoverflow.com/questions/60663930/dask-kubernetes-issue-creating-pod-with-uppercase-username/60664090#60664090

Could add a note to https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/core.py#L279 saying usernames are expected to be lowercase or something along those lines?

**Comment by jacobtomlinson** [comment]
Alternatively, we should sanitise the username by lowercasing the string here.

https://github.com/dask/dask-kubernetes/blob/ac0ef6b95601a350df4173c6e8acf6f15704f574/dask_kubernetes/core.py#L744-L746

**Comment by jacobtomlinson** [comment]
Closing in favour of the reopened #213.
