### ISSUE TITLE
ClusterIP services are not removed after Scheduler and Worker Pods complete 

### ISSUE THREAD

**Issue by andrewwhivery** [dask/dask-kubernetes#248]
When using deploy_mode='remote', the ClusterIP services remain after Scheduler and Worker Pods have completed.

Is there a way of removing these automatically?

```
dask-root-03d5b8bb-0   ClusterIP      10.0.157.39    <none>         8786/TCP,8787/TCP   4m25s

dask-root-07df042f-3   ClusterIP      10.0.247.117   <none>         8786/TCP,8787/TCP   3m7s

dask-root-113ab86f-8   ClusterIP      10.0.22.11     <none>         8786/TCP,8787/TCP   141m

dask-root-16580811-8   ClusterIP      10.0.218.18    <none>         8786/TCP,8787/TCP   5m34s

dask-root-1795ab06-1   ClusterIP      10.0.85.11     <none>         8786/TCP,8787/TCP   129m

dask-root-1fba19ef-6   ClusterIP      10.0.36.190    <none>         8786/TCP,8787/TCP   113m

dask-root-22d99316-5   ClusterIP      10.0.168.67    <none>         8786/TCP,8787/TCP   3h53m

dask-root-300a9f3f-9   ClusterIP      10.0.45.20     <none>         8786/TCP,8787/TCP   89m
```

**Comment by martindurant** [comment]
The function [`_cleanup_resources`](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/core.py#L691) appears to try to find and remove services so either a) the function is not being called (should happen when the cluster object is garbage collected) or b) the label template is not finding the right services. It would be good to have debug logging in that function to find out which. Do you think you can try to do this research?
