### ISSUE TITLE
Calling "cluster.adapt()" multiple times causes strange behavior and `KilledWorker` errors

### ISSUE THREAD

**Issue by somewacko** [dask/dask-kubernetes#250]
I have this minimal example running on a Google Cloud-managed Kubernetes cluster:

```python
import time

import dask
import numpy as np
from dask.distributed import Client
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_dict(...)
client = Client(cluster)

cluster.adapt(maximum=16)
cluster.adapt(maximum=8)

def sample_pi_monte_carlo(sleep_time):
    x = np.random.uniform(-1, 1)
    y = np.random.uniform(-1, 1)
    time.sleep(sleep_time)
    return (np.sqrt(x**2 + y**2) < 1)

results = client.compute([
    dask.delayed(sample_pi_monte_carlo)(0.1)
    for _ in range(1000)
], sync=True)

print("pi is:", 4 * np.mean(results))
```

When I run this, the cluster seems to scale up but workers will terminate immediately, and ultimately this will crash with `KilledWorker`: 
```
KilledWorker: ('sample_pi_monte_carlo-c4b060d1-c020-4aa1-b1ea-9f7fadeb881a', <Worker 'tcp://10.56.4.77:40643', name: 7, memory: 0, processing: 94>)
```

And the logs on the host machine will look like this, showing workers immediately being retired :
```
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Retire worker names (1, 2, 3, 4, 5, 6, 7, 8)
distributed.deploy.adaptive - INFO - Retiring workers [1, 2, 3, 4, 5, 6, 7, 8]
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.56.11.43:33153', name: 12, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.56.11.43:33153
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.56.6.29:35277', name: 6, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.56.6.29:35277
[more register worker / starting worker messages]
...
[more remove worker / removing comms messages]
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.56.6.29:35277', name: 6, memory: 14, processing: 85>
distributed.core - INFO - Removing comms to tcp://10.56.6.29:35277
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.56.4.77:40643', name: 7, memory: 14, processing: 94>
distributed.core - INFO - Removing comms to tcp://10.56.4.77:40643
```

What's interesting is that this only happens for certain values of `cluster.adapt(maximum=N)`. For example, using this code will work fine without crashing:
```python
cluster.adapt(maximum=16)
cluster.adapt(maximum=16)
```

Any idea what might be going on here? I'm using `dask_kubernetes==0.10.1` with `dask/distributed==2.15.0`.

Let me know if there's anything else I can do to help debug. Thanks!

**Comment by martindurant** [comment]
I suppose, workers being spawned, receiving work, and then being killed by kubernetes before the work is done, sounds like a reasonable set of occurrences. In your posted logs, worker 6 registers after it has already been marked for removal, so maybe there's more than can be done on our end. Also, workers ought to have the time to close cleanly before being killed, but that may not be happening.
- can you post the logs of one of the workers that gets killed while working?
- Is this rapid scaling up and down something you really want to do?

**Comment by zo7** [comment]
Yeah, I think what's surprising to me as a user is that calling `.adapt()` twice like that shouldn't have any effect on the cluster (or at least, nothing visible to me). Workers don't get created when `.adapt()` is called, they get created when work is being submitted.

> can you post the logs of one of the workers that gets killed while working?

It's hard to get logs from workers via `kubectl logs` because the pods cycle from "ContainerCreating" to "Terminating" immediately -- they never seem to be in a "Running" state.

Looking at the logs via GCP's "Logging" section, it appears that the terminated workers are getting killed immediately after starting.

```
2020-05-18 14:53:02.000 PDT
"Successfully assigned default/daskkube856nq to ..."
Info
2020-05-18 14:53:03.000 PDT
"Container image "..." already present on machine"
Info
2020-05-18 14:53:03.000 PDT
"Created container dask"
Info
2020-05-18 14:53:03.000 PDT
"Started container dask"
Info
2020-05-18 14:53:18.000 PDT
"Stopping container dask"
```

> Is this rapid scaling up and down something you really want to do?

Not really, but we have a case where we have code that is trying to create a Dask client that is configured in a standard way, like:
```python
def get_client():
    """Function that configures the client in a standard way."""
    cluster = KubeCluster.from_dict(...)
    client = Client(cluster)
    cluster.adapt(maximum=16)

client = get_client()
client.cluster.adapt(maximum=8)
```

We've also had a case in Jupyter notebooks where people are sloppy and call `.adapt()` in multiple subsequent cells.

**Comment by jacobtomlinson** [comment]
I agree that changing the maximum should not be causing workers to be removed. All of the adapting logic is upstream in dask/distributed.

**Comment by zo7** [comment]
Yeah I was wondering that when I was poking around since `dask_kubernetes` doesn't seem to implement any logic for adapting or scaling workers. Perhaps this should be bubbled up to dask/distributed?

**Comment by jacobtomlinson** [comment]
Yeah I think that's a good idea. Would you mind raising this upstream and mentioning this PR?

**Comment by zo7** [comment]
Will do!

**Comment by AndreaGiardini** [comment]
@somewacko Can we close this issue or it's still present?

**Comment by somewacko** [comment]
Yes! I believe this was solved upstream
