### ISSUE TITLE
Add support for passing in yaml template path in main constructor

### ISSUE THREAD

**Issue by jcrist** [dask/dask-kubernetes#254]
In Prefect I'm trying to standardize some of our configuration on specifying a dask cluster class and kwargs for that class. For example:

```python
executor = Executor(
    cluster_class="dask_yarn.YarnCluster",
    cluster_kwargs={"environment": "..."},
)
```

This is proving a bit tricky with dask-kubernetes, since people commonly use the `KubeCluster.from_yaml` classmethod, whereas most other dask cluster implementations the class constructor is the common method. We can support this as well by taking any callable in as `cluster_class`, but it feels a bit wonky.

I'm wondering if y'all might be amenable to adding support for passing in either a dict or a yaml path as `pod_template` in the main constructor? This makes the `from_yaml` and `from_dict` constructors redundant, since all of this would be done in the main constructor.

**Comment by jacobtomlinson** [comment]
I'm definitely in favour of making things more consistent.

Do you suggest we add something like `yaml` and `dict` kwargs to the constructor? Or do you have some other API in mind?

**Comment by jcrist** [comment]
I was thinking we make `pod_template` and `scheduler_pod_template` check for object type before instantiating:

- If a file path, load yaml from file (same as `from_yaml`)
- If a dict, convert to k8s object (same as `from_dict`)
- If a string with newlines, assume it's yaml text and convert from yaml (this is a new code path, but one we might want for prefect)
- Otherwise assume it's already a k8s object, use directly.

Thoughts?

**Comment by jcrist** [comment]
> If a string with newlines, assume it's yaml text and convert from yaml (this is a new code path, but one we might want for prefect)

Actually, I'm not sure if we'll need this. The goal is to be able to pass in the spec in some form as a kwarg (not the path to the spec), and have environment variables still expanded. Currently environment variables are expanded in templates that are provided via `config` alone, but I'm not sure if we'd want to expand them in other contexts.

**Comment by jcrist** [comment]
To better clarify, the goal here is to provide a way to statically specify:

```python
cluster_class = dask_kubernetes.KubeCluster
cluster_kwargs = {...}  # some kwargs to call the class with later
```

but then at runtime when we call:

```
cluster = cluster_class(**cluster_kwargs)
```

somehow have the image name templated in by an environment variable. This is currently doable, but only through dask's config system afaict - I'm trying to find a way to avoid going through the config system if possible. Thoughts @jacobtomlinson? I'm a bit stuck.

**Comment by jacobtomlinson** [comment]
I think type checking in the `__init__` for the template kwargs and just returning the result of `from_yaml`, `from_dict`, etc sounds reasonable.

You could also use the `make_pod_spec` option if you want to grab from the environment outside of the Dask config system.

```python
    >>> from dask_kubernetes import KubeCluster, make_pod_spec
    >>> pod_spec = make_pod_spec(image=os.environ.get("PREFECT_DASK_KUBERNETES_IMAGE"),
    ...                          memory_limit='4G', memory_request='4G',
    ...                          cpu_limit=1, cpu_request=1,
    >>> cluster = KubeCluster(pod_spec)
```

**Comment by davidsheldon** [comment]
Does `cluster_class` have to be a Class?  If you do:

```
cluster_class = dask_kubernetes.KubeCluster.from_yaml
cluster_kwargs = { yaml_path: .... }
```
Then when you call
```
cluster = cluster_class(**cluster_kwargs)
```
