### ISSUE TITLE
Helm command is now a mandatory dependency

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#262]
Unless I'm wrong, this implicitly makes `helm` a new mandatory dependency of `dask-kubernetes`, if that's the case, I think the doc should be updated to mention that.

_Originally posted by @Timost in https://github.com/dask/dask-kubernetes/pull/255#issuecomment-680084182_

**Comment by jacobtomlinson** [comment]
Thanks for raising the flag here @Timost.

It should be an optional dependency for folks who want to use the `HelmCluster` class. However it seems I've introduced a bug which makes it mandatory.

https://github.com/dask/dask-kubernetes/blob/89a3760b8e396236ed62a36d2827f06782cd6f67/dask_kubernetes/helm.py#L14-L19

This probably shouldn't be module scoped. It should only raise for folks using `HelmCluster`.

**Comment by Timost** [comment]
No problem. I got caught by surprise when I updated my `dask-kubernetes` dependency yesterday, I also think it should be optional, I tend to consider Helm a non trivial dependency especially before helm v3 (because of tiller)

**Comment by jacobtomlinson** [comment]
Absolutely, the hard dependency was an accident. It was always meant to be optional. The problem came from importing `HelmCluster` at the top level for convenience. 

Yes I am glad helm 3 made things much easier.
