### ISSUE TITLE
Importing make_pod_spec results in rogue aiohttp session

### ISSUE THREAD

**Issue by kyprifog** [dask/dask-kubernetes#264]
I have some code that I was running that should not have been initializing any sessions.  At the end of the code I received:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x12733df70>
```
I noticed that if I removed:
```
from dask_kubernetes import make_pod_spec
```
it no longer did this.  It appears importing make_pod_spec is all thats needed to start an aiohttp ClientSession.

**Comment by jacobtomlinson** [comment]
My initial guess would be this line is creating an `aiohttp` session but we do not close it anywhere.

https://github.com/dask/dask-kubernetes/blob/89a3760b8e396236ed62a36d2827f06782cd6f67/dask_kubernetes/objects.py#L17

**Comment by kyprifog** [comment]
That was also my guess as well when I glanced at it before making the issue.   I was going to just address it but wanted to create issue first to make sure there wasn't specific reason for it.

**Comment by jacobtomlinson** [comment]
I've updated the library. The warning should be gone now.

**Comment by kyprifog** [comment]
Thanks for the quick response!
