### ISSUE TITLE
ModuleNotFoundError: No module named 'dask_kubernetes'

### ISSUE THREAD

**Issue by joehoeller** [dask/dask-kubernetes#267]
I have set up and deployed to K8s, & launched the dask dashboard and everything is ok. 

**However in my notebook when i use:**

`from dask_kubernetes import HelmCluster`

**It returns:**

```
ModuleNotFoundError  Traceback (most recent call last)
<ipython-input-4-d0c80836d969> in <module>
----> 1 from dask_kubernetes import HelmCluster

ModuleNotFoundError: No module named 'dask_kubernetes'
```

I am running this from the Jupyter notebook that is launched by the Dask helm chart.

**Comment by quasiben** [comment]
I am a little confused here:
> I have set up and deployed to K8s, & launched the dask dashboard and everything is ok.

How did you deploy a dask cluster on k8s ?   

Typically, dask-kubernetes is installed locally and is used to deploy dask on k8s. So when a users sees:
> ModuleNotFoundError  Traceback (most recent call last)

That would mean that they haven't installed dask-kubernetes at all and they resolve that with:
> conda install -c conda-forge dask-kuberentes

**Comment by joehoeller** [comment]
I deployed the helm chart to k8. The helm chart installs dask-Kubernetes
(correct?), and also launches a notebook and a dashboard on the ports of
the pods I specified.

When I run “from dask_kubernetes import...” in that notebook, it returns
that module not found error.

**Comment by joehoeller** [comment]
FYI: I’m trying to use this with RAPDIS, but their Helm chart doesn’t even deploy, its broken.

**Comment by quasiben** [comment]
The helm chart does not install dask-kubernetes.  The helm chart pulls a docker images and runs the image in a pod.  In the case of the rapid/dask helm chart a scheduler and N workers are created

**Comment by joehoeller** [comment]
I want to be able to use it in the notebook for many good reasons. I’ll
have to make my own Helm chart that fulfills my requirements.

This is a personal comment so take this for what it’s worth, but, as a
programmer wouldn’t you want to be able to spin up workers in your notebook
and progmatically control what happens?

**Comment by jacobtomlinson** [comment]
Thanks for raising this @joehoeller.

I'm not sure this is the right place for this issue as your problem appears to be that `dask-kubernetes` is not installed in the docker image deployed by the chart, not that there is any problem with `dask-kubernetes` itself.

Is this from installing the [Dask helm chart](https://github.com/dask/helm-chart)? And if so are you using the default docker images?

**Comment by quasiben** [comment]
@joehoeller You may be interested in this issue where folks have been discussing better integration between jupyterhub and dask+k8s: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/326 .  It is also possible to use something like [dask-gateway](https://gateway.dask.org/usage.html) for launching dask clusters from a notebook if an existing k8s cluster is made available

**Comment by joehoeller** [comment]
We have it fixed.

**Comment by jacobtomlinson** [comment]
@joehoeller that's great to hear!

Would you mind sharing a little info on how you fixed it, just to help out any folks who may find this issue in the future.

**Comment by joehoeller** [comment]
Yeah I will do a PR for a review and merge of changes to the yaml files, as
well as an additional questions.yaml file to be added. Give me some time
plz.
