### ISSUE TITLE
Make a release to match the current state of the documentation

### ISSUE THREAD

**Issue by holdenk** [dask/dask-kubernetes#268]
Hi Y'all I was trying to get started with Dask on Kube (you can see the video https://www.youtube.com/watch?v=0R4XR612yPA ) and I noticed that the documentation ( specifically the Helm part https://kubernetes.dask.org/en/latest/helmcluster.html ) seems to have gotten a little bit ahead of the latest releases on PyPi/Conda https://pypi.org/project/dask-kubernetes/#history 

It might be good to either make a release or have a release version of the documentation which corresponds with the version folks will get from pypi/conda/etc.

**Comment by mrocklin** [comment]
cc @TomAugspurger @quasiben

**Comment by mrocklin** [comment]
Also @holdenk , you my or may not be aware but there are a variety of different kubernetes approaches to Dask.  

You may also want to try out the dask helm chart, dask-gateway, or the daskhub helm chart

**Comment by TomAugspurger** [comment]
@mrocklin I can create a release but I don't have access to upload to PyPI (you, Jacob, and Joe do). Do you want to give me access?

**Comment by TomAugspurger** [comment]
@holdenk I'm watching your video in the background, it's very informative. We really need to do a better job presenting the information about all our dask & kubernetes options.

I updated the docs on https://helm.dask.org/ for helm3. Restructuring the other docs will take longer.

**Comment by mrocklin** [comment]
Tom, I've added you as an owner.

**Comment by TomAugspurger** [comment]
Thanks. Just pushed 0.11.0 to GitHub / PyPI. Should show up on conda-forge in a few hours.

Please do let us know if you have any other issues Holden.
