### ISSUE TITLE
Following quickstart instructions does not result in a working cluster

### ISSUE THREAD

**Issue by holdenk** [dask/dask-kubernetes#274]
**What happened**:

Loop of:

> distributed.scheduler - INFO - Starting worker compute stream, tcp://10.42.2.8:41211
> distributed.core - INFO - Starting established connection
> distributed.scheduler - ERROR - Couldn't gather keys {"('mean_agg-aggregate-bd6b5d0ba8d5dce415f74feccf68818e',)": ['tcp://10.42.2.8:41211']} state: ['memory'] workers: ['tcp://10.42.2.8:41211']
> NoneType: None
> distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.42.2.8:41211', name: 0, memory: 1, processing: 0>
> distributed.core - INFO - Removing comms to tcp://10.42.2.8:41211
> distributed.scheduler - INFO - Lost all workers
> distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://10.42.2.8:41211'], ('mean_agg-aggregate-bd6b5d0ba8d5dce415f74feccf68818e',)
> NoneType: None
> distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('mean_agg-aggregate-bd6b5d0ba8d5dce415f74feccf68818e',)": ('tcp://10.42.2.8:41211',)}
> distributed.scheduler - INFO - Register worker <Worker 'tcp://10.42.2.8:41211', name: 0, memory: 1, processing: 0>

**What you expected to happen**:

Result of 1.0

**Minimal Complete Verifiable Example**:

```python
from dask_kubernetes import KubeCluster
cluster = KubeCluster.from_yaml('worker-spec.yaml', namespace='dask')
cluster.adapt(minimum=1, maximum=100)
# Example usage
from dask.distributed import Client
import dask.array as da

# Connect Dask to the cluster
client = Client(cluster)

# Create a large array and calculate the mean
array = da.ones((1000, 1000, 1000))
print(array.mean().compute())  # Should print 1.0|
```

**Anything else we need to know?**:

Logs from the one worker pod that launches loops on:

> +---------+-------------+-----------+-----------------+
> | Package | This Worker | scheduler | workers         |
> +---------+-------------+-----------+-----------------+
> | blosc   | None        | 1.7.0     | {'1.7.0', None} |
> +---------+-------------+-----------+-----------------+
> distributed.worker - INFO -         Registered to:   tcp://192.168.1.38:37289
> distributed.worker - INFO - -------------------------------------------------
> distributed.core - INFO - Starting established connection
> distributed.worker - INFO - -------------------------------------------------
> distributed.worker - WARNING - Mismatched versions found
> 

Fixed CA issue so no error output in Jupyter when connecting to the k3s cluster.

**Environment**:

- Dask version: 2.28
- Python version: 2.8
- Operating System: ubuntu
- Install method (conda, pip, source): conda

Kubernetes: k3s on a mix of ARM and x86
Client: separate computer on x86

**Comment by quasiben** [comment]
What the message is saying is the blosc is not installed on the worker.  To remove the warning (and hopefully alleviate the underlying issue) you could do one of the 
following things:

1) Install blosc on the image (this would ensure the same compression is used for message passing)
2) remove blosc from the x86 node (this would remove any compression for message passing -- probably easier because you won't have to rebuild the image)

What does `client.scheduler_comm.comm.handshake_info()` return ?

**Comment by mrocklin** [comment]
More broadly, Dask generally expects that it has the same set of libraries
installed on the client and workers.  There is some growing flexibility
here, but it's always best to try to have things match.

**Comment by holdenk** [comment]
Sounds good, I'll give this a shot with removing blosc until I get blosc rebuilt for arm64 properly.

**Comment by holdenk** [comment]
Actually, looks like getting condaforge to build blosc for arm64 was way simpler than I thought, so I'll build a new image and see :)

**Comment by holdenk** [comment]
I got the environments match @quasiben , when I run `client.scheduler_comm.comm.handshake_info()` I get back `{'compression': 'lz4', 'python': (3, 8, 0), 'pickle-protocol': 5}`
However I still get the looping registered too and starting connection along with `- Workers don't have promised key` etc. msgs when I try and run the array example.

In my attempt to guess at what could be wrong I'm thinking maybe a needing a service configured issue that's being swallowed up and reported as keys missing (if I do get svc on the clsuter I don't see anything for for dask). Would that make sense or is this the wrong direction?

**Comment by quasiben** [comment]
Hmm, viewing your video (which is great!) and your comments (also great) leads to me think that the scheduler can't route directly to the workers.  In the current setup (default), the scheduler will start where the client is instantiated.  So you really have:

- Scheduler/Client: separate computer on x86
- Kubernetes: k3s on a mix of ARM and x86

I would guess a wide variety of solutions could work here:
- An `svc` 
- Loadbalancer
- Anything which routes from the scheduler to the workers

We've seen this particular issue in the past (https://github.com/dask/dask-kubernetes/issues/127).  Alternatively, we could try launching the scheduler on the k8s infrastructure with `deploy_mode='remote'`

> cluster = KubeCluster.from_yaml('gpu-worker-spec.yml', deploy_mode='remote')

This would motivate me to write some docs.  Also if you want to sync up over chat to go over this I'd be happy to find some time to help out

**Comment by quasiben** [comment]
@holdenk i'm adding onto a previous doc PR here: https://github.com/dask/dask-kubernetes/pull/272 with language around remote deployments

**Comment by holdenk** [comment]
Awesome, thank you @quasiben :) Which chat system do you use?

**Comment by jacobtomlinson** [comment]
You can find us over on Gitter 😄 

https://gitter.im/dask/dask

**Comment by matusbielik** [comment]
@holdenk Hello, did you find the solution to this problem?

I am facing the very same error messages, but not with k3s but in minikube. Thanks

**Comment by holdenk** [comment]
Hi @matusbielik I did. I wrote it up at - https://scalingpythonml.com/2020/11/03/a-first-look-at-dask-on-arm-on-k8s.html 
I've got a follow up on deploying the notebook inside the cluster not using remote I'll try and finish the words for it this month.
