### ISSUE TITLE
Support optional PDB creation for remote scheduler

### ISSUE THREAD

**Issue by groszewn** [dask/dask-kubernetes#282]
As a way to ensure that the remote scheduler pod is not evicted or restarted by voluntary disruptions, it would be great to have a way to (optionally) create a [PDB](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) for the remote scheduler pod.  We are currently manually applying PDBs to avoid autoscaling events disrupting the scheduler pod.

[This](https://github.com/dask/dask-kubernetes/issues/112) older issue discusses the same concept, but now that `dask-kubernetes` handles (remote) scheduler pod creation maybe it makes sense to optionally create a PDB for it.

If this sounds like a useful addition, I'd be happy to work on it.

**Comment by jacobtomlinson** [comment]
This sounds great! If you're happy to work on it @groszewn then I look forward to reviewing your PR.

**Comment by groszewn** [comment]
Closing as the PR for this feature has been merged.
