### ISSUE TITLE
KubeCluster loses the ability to run commands against a deployed cluster after periods of inactivity.

### ISSUE THREAD

**Issue by drobison00** [dask/dask-kubernetes#286]
Cluster is created as:

```python
cluster = KubeCluster(pod_template=worker_pod, scheduler_pod=sched_pod, deploy_mode='remote')
```

**What happened**:
Initially, all API commands run against the cluster, such as 'scale', 'close', etc.. function as expected. After some period of time, the cluster object fails to authenticate with the cluster and all API commands return a failed status due to being 'unauthorized'.

```
site-packages/dask_kubernetes/core.py", line 81, in close
    await self.core_api.delete_namespaced_pod(name, namespace)
...
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

**What you expected to happen**:
I would expect the cluster object to re-authenticate, or provide some mechanism to re-attach to the created cluster.

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:
Environment is a GKE cluster. Prior to losing the ability to authenticate, everything else functions as expected.

- Dask version: 2.30.0
- Python version: 3.8.6
- Operating System: GKE + CoS
- Install method (conda, pip, source):

**Comment by jacobtomlinson** [comment]
Thanks for raising this @drobison00! This definitely sounds like a bug. 

Are you able to provide the full traceback? It would be helpful to know what the exception was so we can catch it and retry.

**Comment by drobison00** [comment]
Full trace for cluster.scale(n)

```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-13108' coro=<Pod.close() done, defined at /home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/dask_kubernetes/core.py:77> exception=ApiException()>
Traceback (most recent call last):
  File "/home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/dask_kubernetes/core.py", line 81, in close
    await self.core_api.delete_namespaced_pod(name, namespace)
  File "/home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 189, in __call_api
    raise e
  File "/home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 182, in __call_api
    response_data = await self.request(
  File "/home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 220, in DELETE
    return (await self.request("DELETE", url,
  File "/home/drobison/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 187, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: <CIMultiDictProxy('Audit-Id': '642a303b-290c-4bf1-be17-2c6a66dc2a43', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 04 Dec 2020 00:55:45 GMT', 'Content-Length': '129')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

**Comment by jacobtomlinson** [comment]
Thanks! I was after `kubernetes_asyncio.client.exceptions.ApiException`

**Comment by drobison00** [comment]
@jacobtomlinson Any updates on this? If not, do you have any intuition on what's preventing the re-auth from occurring? If I get some extra time I could take a look.

**Comment by drobison00** [comment]
Looks related to this https://github.com/kubernetes-client/python/issues/741

**Comment by jacobtomlinson** [comment]
Sorry I've been out for a while and this is currently on the backlog.

If you have some time to investigate it would be much appreciated.
