### ISSUE TITLE
Getting started/How to develop/bugs

### ISSUE THREAD

**Issue by pvanderlinden** [dask/dask-kubernetes#287]
I'm not sure what the cause is yet, but I run into several issues with dask kubernetes. 
I'm trying to scale the dask tasks. The current implementation runs the cluster in a single container (with dask distributed). The next step is to deploy the cluster in several containers with dask kubernetes.
Issues I ran into while trying to run the dask kubernetes locally with the tasks started locally as well:
- issues to get it to work in general with minikube: you can't communicate to the pods from outside the minikube cluster and the pods inside can't communicate (easily) to the host. This doesn't look like a feasible option.
- With kind I got some of the basics working as long as I don't use deploy_mode='remote'. So far so good
- When I tried to run an actual job is when I ran into issues:
- running adapt will scale up fine, but crashes with timeouts on scaling down. 
- the tasks will never complete, when the client tries to fetch the actual results it will get a not found, and restarts that tasks, which will continue and continue.

Are the last 2 issues due to a bug, or is this because the last two wouldn't actually use the connection the scheduler has with the worker, but rather try to reach to the worker itself? As I can see it is tested with kind, this somehow works. But I can't find how this works, maybe you run the deploy_mode='remote' with the non documented scheduler loadbalancer service?

**Comment by jacobtomlinson** [comment]
Thanks for raising this @pvanderlinden, there's quite a bit to unpack here.

We have documentation on developing locally [here](https://kubernetes.dask.org/en/latest/testing.html). From the order that you listed things I'm guessing this is what you've followed. If you've found problems with the instructions then feedback would be appreciated.

> running adapt will scale up fine, but crashes with timeouts on scaling down

Some more info on this would be appreciated.

> the tasks will never complete, when the client tries to fetch the actual results it will get a not found, and restarts that tasks, which will continue and continue

Again more info on this would be appreciated.

---

For future issues you may find this blog post on [crafting minimal bug reports](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) useful. The conciseness and quantity of things in this issue makes it a little hard to move forwards.

I would be very open to you raising a bunch of issues, either with individual questions such as "How does `deploy_mode='remote'` work?", or bug reports with reproducible examples.

**Comment by pvanderlinden** [comment]
I will leave more details later today. I will do some more digging today. I skipped "running the tests" and just went to running the cluster from my own code, which involves all kinds of things which complicates this. I think the main issue I was encountering was that the documentation wasn't that clear or completely missing for some issues (and because of that is hard to work out if I'm using it in an unsupported way or that I'm hitting a bug, or that I'm missing something). I will probably raise a bunch of issues later today.

I think the main question of my ticket is if it is possible to do the following? @jacobtomlinson 
- locally test this with dask kubernetes and client running outside the cluster including the scheduler with something like minikube/kind.
- in the end run this on a real cluster with dask kubernetes and client running inside the cluster as well

I think if I look at the test docs and makefile it should be possible, but it wasn't entirely clear to me.

**Comment by jacobtomlinson** [comment]
Yes both of those things **should** be possible. Much of this is down to the networking of your kubernetes cluster. 

I'm going to close this out in anticipation of follow up issues with reproducible examples.

Thanks!

**Comment by pvanderlinden** [comment]
Thanks for the clarification. I will open separate issues once I split them up and have some more details.

**Comment by jacobtomlinson** [comment]
I just wanted to head back here and say there is a bunch of work in #304 to hugely simplify the local development requirements of this project.
