### ISSUE TITLE
scheduler plugin support for remote scheduler

### ISSUE THREAD

**Issue by Timost** [dask/dask-kubernetes#294]
Following discussion on https://github.com/dask/distributed/issues/4421#issuecomment-768356145, I'm opening this feature request to implement [scheduler plugin](https://distributed.dask.org/en/latest/plugins.html#scheduler-plugins) support when the scheduler is deployed in `remote` mode (aka: in a k8s pod).

Currently this deployment mode uses the `dask_kubernetes.core.Scheduler` class which doesn't have an `add_plugin` method. The only way to use scheduler plugins with `dask-kubernetes` is to run the scheduler in local mode where the standard `dask.distributed.Scheduler` class is used.

I'm not really sure how the implementation would go as this probably implies some pickling between the client and the remote scheduler.

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

Distributed currently has a client method to [register a worker plugin](https://distributed.dask.org/en/latest/api.html#distributed.Client.register_worker_plugin), perhaps we could do the same for the scheduler.

**Comment by Timost** [comment]
I tried to understand how it works for the worker plugins, here is what I have so far:
1. calling `client.register_worker_plugin`
2. calls `distributed.scheduler.Scheduler.broadcast` which sends a `msg` over comms to every worker with `op`  `plugin-add`. The actual plugin code is serialized using pickle and sent over the comm channel.
3. Each worker has a handler (`distributed.worker.Worker.plugin_add`) associated to the `plugin-add` `op` which deserializes the pickled plugin code and runs the `plugin.setup` method.
4. Internally the scheduler instance keeps track of all the registered plugins so the new workers can have them too.

If we wanted to replicate this in the case of a remote scheduler, I think we would need to do these:
1. add a `register_scheduler_plugin` method to the `Client` class which would either:
    1. pickle the plugin and send it over the comm (Not sure how this would fit in the existing code...), if scheduler is remote
    2. simply call `add_plugin` on the scheduler, if it's not remote
2. add `register_scheduler_plugin` handler to the `Scheduler` class which will deserialize the plugin and call the `add_plugin` method with it.

What do you think ? I probably missed several things.

**Comment by jacobtomlinson** [comment]
Sounds about right!

**Comment by jacobtomlinson** [comment]
Now that `Client.register_scheduler_plugin` exists I think we can close this out.

http://distributed.dask.org/en/stable/api.html#distributed.Client.register_scheduler_plugin

**Comment by Timost** [comment]
Amazing ! :heart: Thank you ! :pray:
