### ISSUE TITLE
Unable to connect to the helm cluster via HelmCluster

### ISSUE THREAD

**Issue by windworship** [dask/dask-kubernetes#307]
**What happened**:
- Install dask cluster using the helm chart dask/dask
- Install dask-kubernetes
- Try to connect to dask via HelmCluster, exception raised!
![image](https://user-images.githubusercontent.com/7194287/110454966-d77ad080-8102-11eb-9509-9f3107564ee8.png)
- Meanwhile, scheduler reports that the connection is closed
![image](https://user-images.githubusercontent.com/7194287/110455068-f24d4500-8102-11eb-8070-d535d63cccb8.png)

**What you expected to happen**:
Successfully connecting to the dask cluster in kubernetes, and it succeeds when I connect to it from the jupyter in kubernetes:

![image](https://user-images.githubusercontent.com/7194287/110455343-4a844700-8103-11eb-918c-581ba7bf900a.png)

**Minimal Complete Verifiable Example**:

```python
from dask_kubernetes import HelmCluster

cluster = HelmCluster("dhub", namespace="dask")
```

**Anything else we need to know?**:
I also tried to export the port via node port by myself and it also failed for the same reason.

**Environment**:

- Dask version: 0.11.0+15.gedddfeb
- Python version: 3.8.5
- Operating System: macOS Big Sur 11.0.1
- Install method (conda, pip, source): source

**Comment by jacobtomlinson** [comment]
I saw the same issues while developing #304. I upgraded my local development Python from 3.7 to 3.8 and the issue went away.

So this is potentially due to a mismatch in Python versions between the client and scheduler.

You said you have 3.8.5 in your local environment. What version is inside the container?

**Comment by windworship** [comment]
> I saw the same issues while developing #304. I upgraded my local development Python from 3.7 to 3.8 and the issue went away.
> 
> So this is potentially due to a mismatch in Python versions between the client and scheduler.
> 
> You said you have 3.8.5 in your local environment. What version is inside the container?

@jacobtomlinson  thanks so much for help!
It is 3.8.0 in scheduler, so I suppose that there is no mismatch between client and scheduler?
![image](https://user-images.githubusercontent.com/7194287/110467847-765af900-8112-11eb-84e4-f6a78674d232.png)

**Comment by windworship** [comment]
Ok, I'll try with a new conda env and hope it will work.

**Comment by jacobtomlinson** [comment]
Thanks for checking that.

Could you also check the versions of dask and distributed in both the local environment and also the image.

```python
import dask
dask.__version__

import distributed
distributed.__version__
```

**Comment by jacobtomlinson** [comment]
(out of curiosity what tool did you use to obscure the paths in your screenshots?)

**Comment by jacobtomlinson** [comment]
Yeah I would also recommend matching dask and distributed versions.

Ah thanks!

**Comment by windworship** [comment]
> Yeah I would also recommend matching dask and distributed versions.
> 
> Ah thanks!

Ok, I'll try it tomorrow. Thanks!

**Comment by windworship** [comment]
> Yeah I would also recommend matching dask and distributed versions.
> 
> Ah thanks!

It worked after I reinstalled the dask and distributed to the same version! Thanks so much for your help! I suggest that we should add a detail illustration for the issue and workaround in the trouble-shooting section of the document. It will be a great help for others in the future if they encounter the same problem.

**Comment by jacobtomlinson** [comment]
> I suggest that we should add a detail illustration for the issue and workaround in the trouble-shooting section of the document.

Absolutely! Do you have any interest in raising a PR to start a troubleshooting documentation section?

**Comment by windworship** [comment]
> > I suggest that we should add a detail illustration for the issue and workaround in the trouble-shooting section of the document.
> 
> Absolutely! Do you have any interest in raising a PR to start a troubleshooting documentation section?

I'd like to help and raise it ASAP after I check out how to contribute to this project.
