### ISSUE TITLE
Update RtD maintainers

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#310]
It seems I am not a maintainer for this project in Read the Docs. 

I need permissions to fix the currently broken `latest` builds. The `master`->`main` renaming has broken things there.

Pinging other RtD maintainers @mrocklin @jrbourbeau @TomAugspurger. Could someone please add me there?

**Comment by TomAugspurger** [comment]
Added `jacobtomlinson` on that project. Do you have access now?

**Comment by jacobtomlinson** [comment]
Thanks @TomAugspurger! All seems good.

**Comment by jacobtomlinson** [comment]
Latest docs are now building correctly again https://kubernetes.dask.org/en/latest/
