### ISSUE TITLE
(GKE) Dask Cluster Always Returning 0 Memory, 0 Workers, 0 Threads

### ISSUE THREAD

**Issue by omarsumadi** [dask/dask-kubernetes#319]
### Background on the Problem
I'm currently following this guide: https://godatadriven.com/blog/develop-locally-scale-globally-dask-on-kubernetes-with-google-cloud/, but I have changed around a few things, namely using a LoadBalancer rather than a ClusterIP to not have to do any proxying / port forwarding.

- I am running a Completely Private cluster on GKE (Internet Access using a NAT, but External IPs only addressed to Load Balancers). The setup is exactly the same as in the article I posted above.
- I am using a locally hosted Jupyter Lab Notbook (run on Localhost NOT inside of my cluster) to test the creation of a Cluster and a Client.
- I haven't created the Dask Cluster solely inside of my Kubernetes Cluster (for instance, in my Django Webserver inside of my Dask Cluster). **I mention this because it could perhaps be a problem in that some connection to the Kubernetes Cluster isn't working well, but that will be elaborated on later.**

### What happened:
Cluster and Client Details are found here:
```Creating scheduler pod on cluster. This may take some time.
<Client: 'tcp://10.1.2.2:8786' processes=0 threads=0, memory=0 B>
KubeCluster(dask-omarsumadi-ba1e72ae-1, 'tcp://104.196.146.82:8786', workers=0, threads=0, memory=0 B)
```

### What you expected to happen:
I expected the output of the Cluster to have 1 process, 1 thread, and 1GB of memory.

### Any Errors?:
No Errors anywhere - not on Kubernetes, not on Dask/Python

### Minimal Reproduceable Example Ran in JupyterLab on WSL2

``` python
import dask
from dask_kubernetes import KubeCluster, make_pod_spec
from dask.distributed import Client

spec = {
    "metadata": {},
    "spec": {
        "restartPolicy": "Never",
        "serviceAccountName": "dask-service-account",
        "containers": [
            {
                "image": "daskdev/dask:2021.3.0",
                "imagePullPolicy": "Always",
                "args": ["dask-worker","--no-bokeh","--death-timeout","60","--nthreads",'1',"--memory-limit",'1GB'],
                "name": "dask-worer",
                "resources": {
                    "requests": {
                        "cpu": "500m",
                        "memory": "1000Mi"
                    },
                    "limits": {
                        "cpu": "500m",
                        "memory": "1000Mi"
                    }
                }
            }
        ]
    }
}
dask.config.set({'distributed.comm.timeouts.connect': '500s'})
dask.config.set({'kubernetes.scheduler-service-type': 'LoadBalancer'})
dask.config.get("kubernetes.scheduler-service-type")

try:
    cluster = KubeCluster(spec, namespace='dask', deploy_mode="remote", scheduler_service_wait_timeout = 120)
    client = Client(cluster)
    print(client)
    print(cluster)
except Exception as Error:
    print("Error Hit")
    print(Error, str(Exception))
```
### Pod Creation Details and Logs Generated by Dask (-o yaml):
Pod Logs with Kubectl Output: https://pastebin.com/FwvAqgd5
Pod Spec: https://pastebin.com/FzLDsU4x

### Scheduler Details and Logs Generated by Dask (-o yaml):
Scheduler Logs with Kubectl Output: https://pastebin.com/n4shGuDP
Scheduler Spec: https://pastebin.com/iGGGKBJZ

### RBAC and Namespace:
RBAC/Namespace: https://pastebin.com/FA2iE0HT

### Environment:

- Dask version: 2021.3.0
- Dask Kubernetes Version: 2021.3.0
- Python version: 3.8.8
- Operating System: WSL2 (Ubuntu)
- Install method (conda, pip, source): JupyerHub on Conda with Dask_Kubernetes installed via pip

**Comment by quasiben** [comment]
I think you also need to call `scale`.  For example adding two workers would be:

> cluster.scale(2)

**Comment by omarsumadi** [comment]
@quasiben I've already tried this unfortunately and it didn't work.

I really appreciate your willingness to help. I'm going to try this again when I get off work (maybe I misremember something)

**Comment by omarsumadi** [comment]
@quasiben 

So some good news - and I'm sort of an idiot.

I just wasn't patient enough.

The cluster needed some more time to recognize that the workers were being attached.

Going to do some further tests tonight - I am just kind of puzzled that the cluster wasn't recognizing that there were workers immediately after its creation even though the pod was being created. Wouldn't this cause issues?

**Comment by omarsumadi** [comment]
Ok - here was my mistake:

I was scaling up my cluster and printing out the cluster status immediately, but the cluster still didn't have enough time to scale up, so it was just telling nothing is ready yet.

### What I want answered:
Should I wait for Cluster Scale Up and Cluster Close to successfully complete? Or can I continue on with calculations first - would I run into trouble?

- For instance, what if I run calculations but my cluster isn't scaled up to what I want it to be?
- For instance, what I return my webserver to my client before completely shutting the cluster down? I've run into asyncio errors before already.

Here's a better implementation:

```python
import random
import string
import os
import dask
import time
from dask_kubernetes import KubeCluster, make_pod_spec
from dask.distributed import Client
spec = {
    "metadata": {},
    "spec": {
        "restartPolicy": "Never",
        "serviceAccountName": "dask-service-account",
        "containers": [
            {
                "image": "daskdev/dask:2021.3.0",
                "imagePullPolicy": "Always",
                "args": ["dask-worker","--no-bokeh","--death-timeout","60","--nthreads",'1',"--memory-limit",'1GB'],
                "name": "dask-worer",
                "resources": {
                    "requests": {
                        "cpu": "500m",
                        "memory": "1000Mi"
                    },
                    "limits": {
                        "cpu": "500m",
                        "memory": "1000Mi"
                    }
                }
            }
        ]
    }
}

# Loadbalancer Implementation
dask.config.set({'distributed.comm.timeouts.connect': '500s'})
dask.config.set({'kubernetes.scheduler-service-type': 'LoadBalancer'})
dask.config.get("kubernetes.scheduler-service-type")

cluster = "To Set"
try:
    cluster = KubeCluster(spec, namespace='dask', deploy_mode="remote", scheduler_service_wait_timeout = 120)
    # Scale the Cluster and Wait Until Scaling takes Effect
    cluster.scale(2)
    while (int(str(cluster).split(",")[2].replace(" workers=", "")) != 2):
        # Cluster takes time to scale up
        time.sleep(2)
    # Print the Cluster Details
    print(cluster)
    # Close the Cluster
    cluster.close()
    while (int(str(cluster).split(",")[2].replace(" workers=", "")) != 0):
        # Cluster takes time to scale down
        time.sleep(2)
    # Check if the Cluster is Dead
    print(cluster)
except Exception as Error:
    print("Error Hit")
    print(Error, str(Exception))
```

**Comment by jacobtomlinson** [comment]
We already have a process for waiting for workers using the client.

```python
cluster = KubeCluster(spec, namespace='dask', deploy_mode="remote", scheduler_service_wait_timeout = 120)
cluster.scale(2)
client = Client(cluster)
client.wait_for_workers(2)
```

I'm curious why you want to specifically wait for all workers though. With your cluster scaling in the background you can begin using it and submitting work. The scheduler will just queue things until workers appear and start processing stuff.

**Comment by omarsumadi** [comment]
@jacobtomlinson 

Hey Jacob - just inexperience with Dask in particular with Production Environments. Two things:
- I wasn't aware we could wait for workers.
- I was concerned about starting to do processing work before workers are available (but you confirmed this is okay to me).
- Waiting for workers on startup is no longer a concern for me, thanks to you Jacob!

On the flipside, I do want to extend what you just mentioned because I am experiencing some abnormalities - now that you brought up some code.

Here's what I ran from your inspiration, and I know I don't need to wait for workers, but I think something is wrong (either on my side or Dask):

```python
<imports and spec taken from my above code to reduce length>

# Loadbalancer Implementation
dask.config.set({'distributed.comm.timeouts.connect': '500s'})
dask.config.set({'kubernetes.scheduler-service-type': 'LoadBalancer'})
dask.config.get("kubernetes.scheduler-service-type")

cluster = "To Set"
try:
    cluster = KubeCluster(spec, namespace='dask', deploy_mode="remote", scheduler_service_wait_timeout = 120)
    # Scale the Cluster and Wait Until Scaling takes Effect
    cluster.scale(2)
    client = Client(cluster)
    client.wait_for_workers(2)
    # Doesn't wait for all the neccessary workers?
    print(client)
    cluster.close()
    client.shutdown()
    client.close()
    print(client)
except Exception as Error:
    print("Error Hit")
    print(Error, str(Exception))
```

This implementation gives you the following results:
```
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f03b8b551c0>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f03b8a74580>
Creating scheduler pod on cluster. This may take some time.
<Client: 'tcp://10.1.2.5:8786' processes=1 threads=1, memory=1000.00 MB>
# Client Result when disconnected (to be expected)
<Client: not connected>
```

I'm getting errors on recurring calls to create a Dask Kubernetes cluster:
- **That the Client isn't shutdown correctly -> Is my implementation not shut down correctly?**
- That even after I wait for workers, it only shows me that my client has 1 worker avaliable.

If I run my above implementation in which I display above (while loops) I get the result:
```
Creating scheduler pod on cluster. This may take some time.
<Client: 'tcp://10.1.2.6:8786' processes=2 threads=2, memory=2.00 GB>
# Client Result when disconnected (to be expected)
<Client: not connected>
```
In addition, subsequent calls work perfectly, whereas if I don't wait for the cluster to scale down completely, I get those asyncio call errors.

My takeaways:
- It seems like I wait for workers isn't working how I am expecting it to work.
- It seems like I have to wait for the cluster to scale down to 0 before closing the client connections to prevent the asyncio errors.
- I might not be doing something right / my client not closing correctly because I am doing wrong / my cluster is not closing correctly because I am doing it wrong.

**Comment by omarsumadi** [comment]
> In my experience, for config to be picked up by a distributed cluster, you have to do something like:
> 
> ```
> def set_config(key: str, value: str) -> str:
>     import dask
>     dask.config.set({key: value})
>     return dask.config.get(key)
> client.run_on_scheduler(set_config, "distributed.comm.timeouts.connect", "300s")
> client.run(set_config, "distributed.comm.timeouts.connect", "300s")
> ```
> 
> but i'm not sure if this is good practice (i.e., if you want to set/change it after creating the cluster).

I've never seen this - I would love to set the Dask Config specifically for one client incase one client needs X settings (such as worker-daemons) and one does not both running in the same interpreter.

However, the Dask Configuration works perfectly fine. I'm currently stuck reconciling what I expect from client.wait_for_workers() and closing the client causing ascio errors if I don't wait for the cluster to scale to 0.

**Comment by jacobtomlinson** [comment]
I've been seeing those warnings recently too. I think there's a shutdown issue somewhere, but it shouldn't affect your work.

I'm going to close this out now. Welcome to the Dask community!

**Comment by omarsumadi** [comment]
Thanks Jacob, yup - I think I'm just over-exaggerating things :)
