### ISSUE TITLE
Support for worker pods with extra containers

### ISSUE THREAD

**Issue by znd4** [dask/dask-kubernetes#320]
In one of the clusters that I work with, every pod is created with an additional proxy container, which messes up [`read_namespaced_pod_log`](https://github.com/dask/dask-kubernetes/blob/634114afccb959ee1da742be8aff43ab1f9be1a1/dask_kubernetes/core.py#L108-L110) because I get a "container name must be provided" error.

Would it be possible to infer the name of the worker container from the worker template and pass `container=container_name`? (Or, if that's too tricky, allow users to pass that in as a kwarg somewhere?)

Thanks :)

Also, if either of those options is feasible + worth adding, I'm down to try writing a PR

**Comment by jacobtomlinson** [comment]
Thanks for raising this @zdog234. That sounds like something we should fix.

We set the container name to `dask-worker` 

https://github.com/dask/dask-kubernetes/blob/634114afccb959ee1da742be8aff43ab1f9be1a1/dask_kubernetes/objects.py#L152

So I guess we could add `container="dask-worker"` to the `read_namespaced_pod_log` here

https://github.com/dask/dask-kubernetes/blob/634114afccb959ee1da742be8aff43ab1f9be1a1/dask_kubernetes/core.py#L108-L110

I *think* the scheduler's container is also called `dask-worker` so perhaps we should also just change that to `dask` or something.

**Comment by zdog234** [comment]
Hmm I think the [quickstart docs](https://kubernetes.dask.org/en/latest/kubecluster.html) set it to `"dask"` in `worker-spec.yaml`

However, because it's configurable, I'd be a bit worried about hard-coding it in case someone changed the container name for some reason. I don't know why someone would, so maybe it is okay to just hardcore it, or hardcore it but let users override it somewhere.

Sorry if that's poorly written; I just woke up. I can try to clarify later

**Comment by jacobtomlinson** [comment]
Hrm good point. 

Perhaps in `dask-kubernetes/dask_kubernetes/core.py` we should inspect the podspec and extract the container name from there. Because your sidecar container won't be listed in that spec.

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
