### ISSUE TITLE
Kubernetes dependency lower than v12 is causing 'Configuration' has no attribute 'get_default_copy'

### ISSUE THREAD

**Issue by bvdr** [dask/dask-kubernetes#322]
**What happened**:
Kubernetes package lower than v. 12 is causing  'Configuration' has no attribute 'get_default_copy'. 
Using `kybernetes` `11.0.0b2`

```bash
Requirement already satisfied: kubernetes in /usr/local/lib/python3.7/site-packages (11.0.0b2)
```
<img width="576" alt="Screenshot 2021-03-24 at 20 03 42" src="https://user-images.githubusercontent.com/4183317/112708210-751f1f80-8eb9-11eb-9b3f-af134be7e0ae.png">

**Error**:
```
File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/__init__.py", line 3, in <module>
    from .core import KubeCluster
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 19, in <module>
    from .objects import (
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/objects.py", line 34, in <module>
    SERIALIZATION_API_CLIENT = DummyApiClient()
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/objects.py", line 28, in __init__
    self.configuration = Configuration.get_default_copy()
AttributeError: type object 'Configuration' has no attribute 'get_default_copy'
```

**Possible solution**:
I fixed it locally by installing `kubernetes 12.0.1` as a project dependency.
Maybe bump kubernetes version in: https://github.com/dask/dask-kubernetes/blob/634114afccb959ee1da742be8aff43ab1f9be1a1/requirements.txt ?

**Environment**:

- Dask version: `dask_kubernetes-2021.3.0`
- Python version: `3.7`
- Operating System: `linux`
- Install method (conda, pip, source): `pip install`

**Comment by jacobtomlinson** [comment]
Thanks for raising this.
