### ISSUE TITLE
Connect the exisng scheduler pod to deploy works pods based on needs

### ISSUE THREAD

**Issue by gudipudipradeep** [dask/dask-kubernetes#326]
We are trying to connect the dask scheduler to deploy the pods based on configurations.
host & port are the running scheduler pod inside the cluster to connect.

from dask_kubernetes import KubeCluster
cluster = KubeCluster(pod_spec1, host="192.168.171.113", port="8786") 
client = Client(cluster) 
cluster.scale(5)

existing scheduler I need to connect and specify the pods before running.
but when running above code it trying to create the scheduler it is not using existing scheduler.

**Comment by jacobtomlinson** [comment]
`KubeCluster` does not support connecting to an existing scheduler. Sorry!
