### ISSUE TITLE
Dask Worker not able to communicate with scheduler 

### ISSUE THREAD

**Issue by jayanta5050** [dask/dask-kubernetes#327]
I am running kubernetes cluster on prem server  ( 3 node cluster    one master and 2 worker.)
- Dask version:
              - dask               2021.3.0
                dask-k8            0.1.1
                dask-kubernetes    2021.3.0
                distributed        2021.3.0
                kubernetes         12.0.1
                kubernetes-asyncio 12.1.0

- Python version: python3.8
- Operating System: Red Hat 7
- Install method (conda, pip, source): source

I am able to create dask pods are one scheduler and 2 worker, all pods are running fine
in worker pods i can see it waiting for connection to scheduler, also logs i can see error

/opt/conda/lib/python3.8/site-packages/distributed/utils.py:146: RuntimeWarning: Couldn't detect a suitable IP address for reaching 'dask-h235213a-9540fff0-5.default', defaulting to hostname: [Errno -3] Temporary failure in name resolution

kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
dask-h235213a-9540fff0-58g45c   1/1     Running   0          33m
dask-h235213a-9540fff0-5gvqn8   1/1     Running   0          33m
dask-h235213a-9540fff0-5sbr64   1/1     Running   0          34m

work pod logs
---------------------------------------------------------------------------------------
+ exec dask-worker tcp://dask-h235213a-9540fff0-5.default:8786 --nthreads 2 --dashboard --memory-limit 6GB --death-timeout 60000 --name 0
/opt/conda/lib/python3.8/site-packages/distributed/utils.py:146: RuntimeWarning: Couldn't detect a suitable IP address for reaching 'dask-h235213a-9540fff0-5.default', defaulting to hostname: [Errno -3] Temporary failure in name resolution
  warnings.warn(
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.210.31:41482'
/opt/conda/lib/python3.8/site-packages/distributed/utils.py:146: RuntimeWarning: Couldn't detect a suitable IP address for reaching 'dask-h235213a-9540fff0-5.default', defaulting to hostname: [Errno -3] Temporary failure in name resolution
  warnings.warn(
distributed.worker - INFO -       Start worker at:  tcp://172.16.210.31:39424
distributed.worker - INFO -          Listening to:  tcp://172.16.210.31:39424
distributed.worker - INFO -          dashboard at:        172.16.210.31:45391
distributed.worker - INFO - Waiting to connect to: tcp://dask-h235213a-9540fff0-5.default:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    6.00 GB
distributed.worker - INFO -       Local Directory: /dask-worker-space/worker-26mk01vv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to: tcp://dask-h235213a-9540fff0-5.default:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-h235213a-9540fff0-5.default:8786

Is i am missing some configuration? 
Thanks

![image](https://user-images.githubusercontent.com/79866150/114042959-dfd64080-9853-11eb-8594-1ca422193d0c.png)

**Comment by jacobtomlinson** [comment]
Are you running any services like Istio which may interfere with pod-pod communication?

**Comment by jayanta5050** [comment]
Thanks Jacob for your comment.

Nope i a not running Istio.

List  of service i can see in the server are below
UNIT                                           LOAD   ACTIVE SUB     DESCRIPTION
abrt-ccpp.service                              loaded active exited  Install ABRT coredump hook
abrt-oops.service                              loaded active running ABRT kernel log watcher
abrtd.service                                  loaded active running ABRT Automated Bug Reporting Tool
atd.service                                    loaded active running Job spooling tools
auditd.service                                 loaded active running Security Auditing Service
blk-availability.service                       loaded active exited  Availability of block devices
crond.service                                  loaded active running Command Scheduler
dbus.service                                   loaded active running D-Bus System Message Bus
docker.service                                 loaded active running Docker Application Container Engine
enlinuxpc.service                              loaded active running SYSV: Honeywell Internal-use Daemon
getty@tty1.service                             loaded active running Getty on tty1
gssproxy.service                               loaded active running GSSAPI Proxy Daemon
iptables.service                               loaded active exited  IPv4 firewall with iptables
ir_agent.service                               loaded active running Rapid7 Insight Agent
irqbalance.service                             loaded active running irqbalance daemon
iscsi-shutdown.service                         loaded active exited  Logout off all iSCSI sessions on shutdown
kdump.service                                  loaded active exited  Crash recovery kernel arming
kmod-static-nodes.service                      loaded active exited  Create list of required static device nodes for the current kernel
ksm.service                                    loaded active exited  Kernel Samepage Merging
ksmtuned.service                               loaded active running Kernel Samepage Merging (KSM) Tuning Daemon
kubelet.service                                loaded active running kubelet: The Kubernetes Node Agent
libstoragemgmt.service                         loaded active running libstoragemgmt plug-in server daemon
lvm2-lvmetad.service                           loaded active running LVM2 metadata daemon
lvm2-monitor.service                           loaded active exited  Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling
lvm2-pvscan@8:17.service                       loaded active exited  LVM2 PV scan on device 8:17
lvm2-pvscan@8:3.service                        loaded active exited  LVM2 PV scan on device 8:3
mdatp.service                                  loaded active running Microsoft Defender ATP
netbackup.service                              loaded active running LSB: NetBackup
network.service                                loaded active exited  LSB: Bring up/down networking
ntpd.service                                   loaded active running Network Time Service
ntpdate.service                                loaded active exited  Set time via NTP
oddjobd.service                                loaded active running privileged operations for unprivileged applications
packagekit.service                             loaded active running PackageKit Daemon
polkit.service                                 loaded active running Authorization Manager
rc-local.service                               loaded active exited  /etc/rc.d/rc.local Compatibility
rhel-dmesg.service                             loaded active exited  Dump dmesg to /var/log/dmesg
rhel-domainname.service                        loaded active exited  Read and set NIS domainname from /etc/sysconfig/network
rhel-import-state.service                      loaded active exited  Import network configuration from initramfs
rhel-push-plugin.service                       loaded active running Docker Block RHEL push plugin authZ Plugin
rhel-readonly.service                          loaded active exited  Configure read-only root support
rhsmcertd.service                              loaded active running Enable periodic update of entitlement certificates.
rngd.service                                   loaded active running Hardware RNG Entropy Gatherer Daemon
rpc-gssd.service                               loaded active running RPC security service for NFS client and server
rsyslog.service                                loaded active running System Logging Service
sendmail.service                               loaded active running Sendmail Mail Transport Agent
sm-client.service                              loaded active running Sendmail Mail Transport Client
sshd.service                                   loaded active running OpenSSH server daemon
sssd.service                                   loaded active running System Security Services Daemon
sysstat.service                                loaded active exited  Resets System Activity Logs
systemd-binfmt.service                         loaded active exited  Set Up Additional Binary Formats
systemd-fsck@dev-mapper-400vg\x2d400lv.service loaded active exited  File System Check on /dev/mapper/400vg-400lv
systemd-journal-flush.service                  loaded active exited  Flush Journal to Persistent Storage
systemd-journald.service                       loaded active running Journal Service
systemd-logind.service                         loaded active running Login Service
systemd-modules-load.service                   loaded active exited  Load Kernel Modules
systemd-random-seed.service                    loaded active exited  Load/Save Random Seed
systemd-remount-fs.service                     loaded active exited  Remount Root and Kernel File Systems
systemd-sysctl.service                         loaded active exited  Apply Kernel Variables
systemd-tmpfiles-setup-dev.service             loaded active exited  Create Static Device Nodes in /dev
systemd-tmpfiles-setup.service                 loaded active exited  Create Volatile Files and Directories
systemd-udev-settle.service                    loaded active exited  udev Wait for Complete Device Initialization
systemd-udev-trigger.service                   loaded active exited  udev Coldplug all Devices
systemd-udevd.service                          loaded active running udev Kernel Device Manager
systemd-update-utmp.service                    loaded active exited  Update UTMP about System Boot/Shutdown
systemd-user-sessions.service                  loaded active exited  Permit User Sessions
systemd-vconsole-setup.service                 loaded active exited  Setup Virtual Console
tuned.service                                  loaded active running Dynamic System Tuning Daemon
vdo.service                                    loaded active exited  VDO volume services
vgauthd.service                                loaded active running VGAuth Service for open-vm-tools
vmtoolsd.service                               loaded active running Service for virtual machines hosted on VMware
vxpbx_exchanged.service                        loaded active running SYSV: Provides Veritas Private Branch Exchange

**Comment by jayanta5050** [comment]
![image](https://user-images.githubusercontent.com/79866150/114186368-be895900-9914-11eb-9df8-e507f62eaa7d.png)

**Comment by jayanta5050** [comment]
![image](https://user-images.githubusercontent.com/79866150/114186473-e7a9e980-9914-11eb-990f-0d5ab0baae91.png)

**Comment by jacobtomlinson** [comment]
Thanks.

It seems like this is a DNS issue within your cluster. The workers are not able to resolve the IP address of the scheduler pod.

Are you the k8s cluster admin? Or are you using a cluster that has been provided for you?

**Comment by jayanta5050** [comment]
I am the k8s cluster admin

**Comment by jacobtomlinson** [comment]
How did you deploy kubernetes? It sounds like the coredns service isn't running properly.

**Comment by jayanta5050** [comment]
I followed this page to install Kubernetes.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by jayanta5050** [comment]
I can see the coredns pod
kube-system   coredns-74ff55c5b-hxrsh                              1/1     Running   0          22d
kube-system   coredns-74ff55c5b-tvqcv                              1/1     Running   0          22d

**Comment by jacobtomlinson** [comment]
Sure, but if you run a shell in a pod are you able to resolve DNS names of pods and services?

**Comment by jayanta5050** [comment]
looks like port 53 is closed for my three machines, I opened this port 53

k-master 
k-worker 1   scheduler pod , dask-worker1 pod
k-worker 2.  dask-worker2 pod, dask-worker3 pod

dask-worker2 and dask-worker3 is able to resolve the dns of the scheduler but dask-worker1 is not able to resolve the dsn name of the Scheduler.

**Comment by jacobtomlinson** [comment]
I'm glad you've been able to make some progress here and that you can confirm it is a DNS issue on your cluster.

I'm afraid we can't support everyone and their individual cluster setups. Perhaps you should direct your questions to the Kubernetes community to help you get your DNS configured correctly.

Sorry!

**Comment by jayanta5050** [comment]
I agree, it is Kubernetes issue. 
Thanks Jacob for your help. I am closing this issue.
