### ISSUE TITLE
Scheduler doesn't exit when the controlling client exits.

### ISSUE THREAD

**Issue by pvanderlinden** [dask/dask-kubernetes#343]
**What happened**:
The scheduler should exit after it is idle for a certain amount of time. But if I force kill the client (kill -KILL the process with dask_kubernetes), the containers will continue running. If I set `distributed.scheduler.idle-timeout` to something low, I can see the containers go to completion status, but then restart again.

**What you expected to happen**:
In the old default mode (now `deploy_mode="local"`) everything was cleaned up, even if you force kill the process with `dask_kubernetes` running.

**Comment by jacobtomlinson** [comment]
This is expected behaviour. 

By launching all components on the Kubernetes cluster we are fully decoupled from the Python process which created them. We attempt to clean up resources when the cluster object is closed or deleted, but if you `kill -KILL` the process then this will not be possible.

If you want to keep the old behaviour then you still have `deploy_mode="local"`.

I appreciate that today we don't have a neat way to clean up resources in this failure mode, but this is why [dask-ctl](https://github.com/dask-contrib/dask-ctl) exists. Adding support for `dask-ctl` here is on the roadmap.

**Comment by pvanderlinden** [comment]
Dask-ctl didn't actually exist when dask kubernetes started.  In the reference ticket you mention that the scheduler should actually die on idle?

**Comment by jacobtomlinson** [comment]
> Dask-ctl didn't actually exist when dask kubernetes started.

That's true. We are working on it now to fill this need.

>  In the reference ticket you mention that the scheduler should actually die on idle?

You're right that setting the [idle-timeout](https://docs.dask.org/en/latest/configuration-reference.html#distributed.scheduler.idle-timeout) option should cause the scheduler process to exit after a period of inactivity.

Given that the scheduler pod is created directly and has no controlling object (like a Deployment) it should stay in `Completed` once the process exits. Do you have something on your Kubernetes cluster which is restarting completed pods?

**Comment by pvanderlinden** [comment]
This is actually a clean minikube cluster for testing, so only native functionality. It sounds like we are better off sticking with local deployment mode until dask-ctl is ready.

**Comment by jacobtomlinson** [comment]
Strange, I've not known `Completed` pods to restart.

Fair enough. There should be no problem with using the `local` deploy mode. I hope to get `dask-ctl` support into `dask-kubernetes` in the near future.

**Comment by pvanderlinden** [comment]
I think that has always been the default behaviour, unless specified otherwise

**Comment by jacobtomlinson** [comment]
According to [the docs here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) if all processes in a container succeed the pod will not be restarted.

> All containers in the Pod have terminated in success, and will not be restarted.

**Comment by pvanderlinden** [comment]
I'm a bit confused about that doc. First, it's missing the phase `completed`.

Also:
| The spec of a Pod has a restartPolicy field with possible values Always, OnFailure, and Never. The default value is Always.

This is also why you would normally set the pod spec for a kubernetes job to set this field to `Always`, see https://kubernetes.io/docs/concepts/workloads/controllers/job/#writing-a-job-spec

Maybe it would be better to add this settings by default to the scheduler? (`restartPolicy: OnFailure`, and a default for `distributed.scheduler.idle-timeout`).

**Comment by jacobtomlinson** [comment]
> Maybe it would be better to add this settings by default to the scheduler? (restartPolicy: OnFailure, and a default for distributed.scheduler.idle-timeout).

That sounds reasonable. Do you have any interest in submitting a PR?

**Comment by pvanderlinden** [comment]
Sure, I will find some time for it this week.

**Comment by jacobtomlinson** [comment]
Given the lack of activity here and we've had no other users reporting these issues I'm going to close this out. Feel free to comment back here if this is still desirable though.
