### ISSUE TITLE
Unable to create KubeCluster instance

### ISSUE THREAD

**Issue by pthalasta** [dask/dask-kubernetes#361]
**What happened**: Unable to create dask-kubernetes cluster instance

**What you expected to happen**: create a cluster for dask with dask-kubernetes

**Minimal Complete Verifiable Example**:

```python
cluster = KubeCluster('worker-spec.yml')

```
Above code is taken from quick start sample at https://kubernetes.dask.org/en/latest/kubecluster.html

**Anything else we need to know?**:

**Environment**: Kubeflow 1.3, Amazon EKS kubernetes environment

- Dask version: dask_kubernetes-2021.3.1, dask-2021.5.0
- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): conda

Error message:
```
ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'df2414d7-as72-43dd-9ea9-7c90e5b21e80', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 10 Sep 2021 16:13:40 GMT', 'Content-Length': '229')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod dask-root-1312e4f2-3ads6p, choose one of: [istio-init dask istio-proxy]","reason":"BadRequest","code":400}
```

**Comment by jacobtomlinson** [comment]
There are known issues with running `dask-kubernetes` with `istio`. Please see #197

**Comment by jacobtomlinson** [comment]
Closing in favour of #197
