### ISSUE TITLE
Specifying a scheduler_pod_template of the same value of pod_template fails

### ISSUE THREAD

**Issue by holdenk** [dask/dask-kubernetes#363]
**What happened**:

The scheduler pod errors with ```ValueError: missing port number in address '$(DASK_SCHEDULER_ADDRESS)'```

**What you expected to happen**:

Scheduler to start (based on A Kubernetes specification for a Pod for a dask scheduler. Defaults to the pod_template. in the docs).

**Minimal Complete Verifiable Example**:

```python
pod_spec = make_pod_spec(image='holdenk/dask:latest',
                         memory_limit='8G', memory_request='8G',
                         cpu_limit=1, cpu_request=1)
cluster = KubeCluster(namespace='dask', pod_template=pod_spec, scheduler_pod_template=pod_spec)
```

**Anything else we need to know?**:

I think it can be fixed by rewriting the command args or updating the docs to make that clear to the user.

**Comment by holdenk** [comment]
If anyone is running into this a workaround is to, on your scheduler_pod_template only:

```python
scheduler_pod_spec.spec.containers[0].args = ["dask-scheduler"]
```

**Comment by jacobtomlinson** [comment]
The workaround you shared already happens during the cluster startup. So it's strange that it solves the issue.

https://github.com/dask/dask-kubernetes/blob/7446cdbb68e4b566c5bb82f0f5107dbd5dcf378a/dask_kubernetes/core.py#L528

**Comment by holdenk** [comment]
That makes sense given the git history & pypi release timeline. The workaround was added in the dask-Kubernetes code ~6 months ago and the last dask-Kubernetes release was (I think time wise) right before that.

**Comment by holdenk** [comment]
Closed since workaround is already implemented just not released.
