### ISSUE TITLE
Best practice for dask-kubernetes and adaptive deployments when application in separate docker container?

### ISSUE THREAD

**Issue by ShaneMill1** [dask/dask-kubernetes#366]
Hi all,

I am developing an API for the National Weather Service that reaches to backend chunked Zarr datastores as a data backend. This API is deployed within a docker container. I would love to take advantage of a dask adaptive deployment. So, when a query is made, dask workers would scale up to fulfill the request and scale back down.

The API is currently a docker container. I have investigated using a DockerinDocker container to run Kubernetes in docker, in order to run dask-kubernetes. This would then have to be my base docker environment for the API deployment. I think this seems a little hacky though.

Are there use cases for running an application in a separate container and then being able to connect that environment to a kubernetes cluster that can run dask-kubernetes to fulfill requests? Because running Docker in Docker seems a little hacky.

Status of development so far:

Conclusions

- Created a test container that is able to run python with dask-kubernetes.
- The issue is that docker is within this container (docker in docker) in order to run kind (kubernetes in docker).
- According to (https://github.com/kubernetes-sigs/kind/issues/706), that is the recommended way to run kind when it is needed in a container. In this issue, the person asks if kind can be run as a docker-compose service which would be ideal for the EDR, and the creator of kind basically says no, and that docker in docker is recommended.
- I will need to create a ticket in dask-kubernetes asking the recommended way to run kubernetes when a docker containerized application wants access to dask-kubernetes and the scaling it provides.
- I would recommend holding off on changing the EDR deployment for now until we get clarification on a recommended workflow because running the EDR within this current test container would change the deployment.

Any feedback for the appropriate workflow here would be very much appreciated. Full disclosure, I am new to kubernetes so am working to get caught up to speed there.

**Comment by jacobtomlinson** [comment]
If you're trying to run Kubernetes inside a single container alongside your API service then you are going to have a hard time scaling that up.

Kubernetes should be your base platform, running on many servers or using a managed service. Then you can run `dask-kubernetes` on top. You could also run your API container on Kubernetes as a service.

How are you currently deploying your API container, and how many instances of that container are you running? Just one or multiple?

**Comment by jacobtomlinson** [comment]
This conversation seems to have come to a natural end. Closing this out. Feel free to head over to our [forum](https://dask.discourse.group/) if you have any further Dask questions @ShaneMill1.
