### ISSUE TITLE
NoCredentialsError: Unable to locate credentials when reading from S3

### ISSUE THREAD

**Issue by mb-qco** [dask/dask-kubernetes#372]
I use a wrapper class around `KubeCluster()` that creates a KubeCluster object when an instance of my class is created.

This means the KubeCluster can be accessed like this:

```
my_cluster.kubecluster
```

I am able to do things like `my_cluster.kubecluster.scale(N)` and this functionality seems to be just fine.

Under the hood, I have deployed the cluster autoscaler for EKS. This scales up the right EKS Managed Node groups whenever `.scale(N)` is invoked.

To the Dask worker EKS Managed Node Group, I have added an instance profile which gives the Pod access to read from my S3 buckets. 

I am able to SSH into the underlying Node and do `aws s3 ls <my-bucket>`.
Additionally, I am able to SSH into the dask worker Pod, install the `awscli` tool and run the same `aws s3 ls <my-bucket>` command without encountering any authentication issue.

I want to be able to execute this command from my Jupyter Notebook:

```
data = dd.compute(dd.read_csv('s3://<my-bucket>/.csv.gz'))
```

**What happened**:

I get a:

```
NoCredentialsError: Unable to locate credentials
```
Note that the correct execution of `aws s3 ls <my-bucket>` from the pod itself implies that credentials are available to the Pod.

**What you expected to happen**:

I expect the command to succeed without any error.

When I use the same command on a static Dask Distributed cluster, it results in no errors.

**Anything else we need to know?**:

I run my Jupyter Notebooks on separate instances. These are outside of both the static Dask Distributed and the dynamic Dask Kubernetes clusters. The Dask Kubernetes Schedulers, created from my wrapper class, are exposed to the Jupyter Notebook with an internal LB and I am able to create dask.distributed.Client instances  without any problem.

**Environment**:

- Dask version: 2021.9.1 and 2021.10.0
- Python version: 3.8.12
- Operating System: Whichever Dask Kubernetes uses
- Install method (conda, pip, source): Conda

**Comment by jacobtomlinson** [comment]
Does your Jupyter Notebook also have the correct access to S3?

Also I would advise against `data = dd.compute(dd.read_csv('s3://<my-bucket>/.csv.gz'))`. This will read all the data from S3 through the Dask workers and transfer the whole lot into memory on your notebook.

Instead, you may want to use `.persist()` which reads into memory on the workers.

```python
data = dd.read_csv('s3://<my-bucket>/.csv.gz').persist()
```

**Comment by mb-qco** [comment]
@jacobtomlinson thank you for getting back to me on this.

Would the Jupyter Notebook instance requires these? Ideally the Jupyter Notebook doesn't have the same privileges as the worker nodes. In example, they may be more lax, or strict.

**Comment by jacobtomlinson** [comment]
I would advise against making assumptions about what is and isn't needed on the client. We always recommend that the client, scheduler and workers all have consistent environments. This includes credentials.

Are you able to connect to the pod and start an interactive Python session and then use Pandas to read the same CSV file?

**Comment by mb-qco** [comment]
@jacobtomlinson thanks for the advice. Yeah, this works.

**Comment by jacobtomlinson** [comment]
And does the same work from the notebook environment (without Dask).

**Comment by mb-qco** [comment]
@jacobtomlinson  Yep, the permissions are the same.

**Comment by jacobtomlinson** [comment]
If `pd.read_csv` works from within the container but `dd.read_csv` doesn't then that suggests there is something wrong with the way Dask is reading from S3.

I'm not sure this repo is the right place to troubleshoot this though as `KubeCluster` seems to be working as expected.

Would you mind opening a thread on [the forum](https://dask.discourse.group/) instead?

**Comment by jacobtomlinson** [comment]
Closing due to conversation being redirected to the forum.
