### ISSUE TITLE
Enable AutoRefreshKubeConfigLoader ExecPlugin support

### ISSUE THREAD

**Issue by gregoiregermain** [dask/dask-kubernetes#388]
Related to #317 

### Current behavior

The AutoRefreshKubeConfigLoader overwrites KubeConfigLoader following methods:
 - _load_oid_token
 - load_gcp_token

Get the expiration timestamp of the provided token and create a task than run before the token expiration.
The user authentification method with an executable:
```
"exec" in self._user
```
is not supported and the warning in the refresh_after method is not logged because the kubernetes_asyncio KubeConfigLoader._load_from_exec_plugin is not overwritten.

### Desired Behavior

We should be able to get the expiration timestamp from the response of the executable and use it to make the auto refresh supporting executable plugin authentification method.

**Comment by jacobtomlinson** [comment]
Thanks for reporting this. Do you have any interest in raising a Pull Request?

**Comment by gregoiregermain** [comment]
Yes sure!

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
