### ISSUE TITLE
'HelmCluster' object has no attribute 'status' when connecting to Dask release on GKE

### ISSUE THREAD

**Issue by VBenedetto** [dask/dask-kubernetes#416]
**What happened**: I've deployed dask helm chart on gke, can access to the cluster with distributed.Client.
Now I need to connect to dask cluster with dask_kubernetes.HelmCluster, but it raises this exception. Code works in my local environment, but raises exception in GCE. Cluster is already accessible with kubectl.

```python
from dask_kubernetes import HelmCluster

cluster = HelmCluster(release_name='my-dask')
```

**Environment**:

- Dask version: 2021.11.0
- Python version: 3.8.0
- Dask-kubernetes version: 0.11.0 and 2022.1.0

**Comment by jacobtomlinson** [comment]
Could you please include the exception.

**Comment by VBenedetto** [comment]
```
RuntimeError: Missing dependency kubectl. Please install kubectl following the instructions for your OS. 
Exception ignored in: <function Cluster.__del__ at 0x7fa65a330b80>
Traceback (most recent call last):
  File "/***path***/.local/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 196, in __del__
    if self.status != Status.closed:
AttributeError: 'HelmCluster' object has no attribute 'status'
```
Anyway, previously I installed kubectl via gcloud components, maybe it made kubectl unreachable from HelmCluster object, re-installing it from default repo fixed the problem.

**Comment by RahulJangir2003** [comment]
> ```
> RuntimeError: Missing dependency kubectl. Please install kubectl following the instructions for your OS. 
> Exception ignored in: <function Cluster.__del__ at 0x7fa65a330b80>
> Traceback (most recent call last):
>   File "/***path***/.local/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 196, in __del__
>     if self.status != Status.closed:
> AttributeError: 'HelmCluster' object has no attribute 'status'
> ```
> 
> Anyway, previously I installed kubectl via gcloud components, maybe it made kubectl unreachable from HelmCluster object, re-installing it from default repo fixed the problem.

Hey I am having this same error when i am using yarncluster i have downloaded the packages using conda(bootstrap script provided by dask docs). what should i do?

**Comment by ahzaz** [comment]
@RahulJangir2003 Please check https://github.com/dask/dask-yarn/issues/155
