### ISSUE TITLE
No handlers could be found for logger "dask_kubernetes.cli.utils"

### ISSUE THREAD

**Issue by ajkl** [dask/dask-kubernetes#43]
$ dask-kubernetes create test
No handlers could be found for logger "dask_kubernetes.cli.utils"

Got the same error on ubuntu 14.04 and on a mac

**Comment by martindurant** [comment]
That is strange. I have not seen the error - does it halt execution at this point?
In the code, function `cli()` is called first, which sets up logging in general, so I don't see how this happens. Can you please list your versions?

**Comment by ajkl** [comment]
Sorry for the delay in response. What versions are you referring to ?
Looking forward to using this! Let me know how I can help and what all more information you need.

**Comment by ajkl** [comment]
Closing. this was an issue because of confusion between default python and anaconda installation on my part.
