### ISSUE TITLE
Error connecting to the scheduler

### ISSUE THREAD

**Issue by ajkl** [dask/dask-kubernetes#45]
I got the cluster successfully spawned and it showed a message like this 
```
Addresses
---------
   Web Interface:  http://104.196.202.253:8787/status
Jupyter Notebook:  http://35.185.38.137:8888
     Jupyter Lab:  http://35.185.38.137:8889
Config directory:  /Users/ajkale/.dask/kubernetes/dask-cluster-1
 Config settings:  /Users/ajkale/.dask/kubernetes/dask-cluster-1.yaml

To connect to scheduler inside of cluster
-----------------------------------------
from dask.distributed import Client
c = Client('dask-scheduler:8786')

or from outside the cluster

c = Client('104.196.202.253:8786')

Live pods:
{u'dask-scheduler': [u'dask-scheduler-9hkw6'], u'jupyter-notebook': [u'jupyter-notebook-4jzr2'], u'dask-worker': [u'dask-worker-mdr4z']}
```

Couple of issues - 
1. The jupyter notebook and lab need a password. Didnt find an easy way to get those.
2. From outside the cluster if I try `c = Client('104.196.202.253:8786')` as mentioned in the info, I get this error

```
distributed.utils - ERROR - in <closed TCP>: Stream is closed: while trying to call remote method 'identity'
Traceback (most recent call last):
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 680, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 716, in _ensure_connected
    yield self.scheduler.identity()
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ajkale/anaconda2/lib/python2.7/site-packages/distributed/core.py", line 433, in send_recv_from_rpc
    % (e, key,))
CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'identity'```

**Comment by martindurant** [comment]
The [readme](https://github.com/dask/dask-kubernetes/blob/master/README.md) specifies the password: `jupyter`.
The connection error is stranger: I can confirm that things work for me. You should know that the docker image used by this project is regularly rebuilt, and so has the latest versions of all of the packages, including python, dask, distributed etc.  You will need the same versions locally in order to connect.

**Comment by ajkl** [comment]
My bad, didnt read the docs for the password.
I will try it in a conda env which will match all the versions in the docker image.

**Comment by martindurant** [comment]
One helpful simplification would be to pull out the package lists from the docker file into an `environment.yaml` and call `conda-create` on that - so then you have the same environment file available locally too and can make identical environments.
Perhaps I could add a `dask-kuberenetes client` command to build/update such an environment and start ipython with `client = Client(...)` connecting to the local cluster.

**Comment by ajkl** [comment]
@martindurant also not sure if this is something to do with auth on my GCP setup. I just got the jupyter lab running and tried few examples through the notebook instead of my local and it seems there might be some connection issues. The cluster setup doesnt look right -
<img width="721" alt="screen shot 2017-07-17 at 11 17 01 am" src="https://user-images.githubusercontent.com/4917183/28283239-08ef2d0e-6ae2-11e7-908d-9216fa8a2b5c.png">

**Comment by martindurant** [comment]
You have no workers... In your original print-out, you had only one worker pod live, which perhaps didn't have enough memory to launch (this can happen) - are you using fewer nodes and smaller memory than the defaults?

**Comment by ajkl** [comment]
Nope, didnt change any of the defaults. You were right the one worker pod was in bad state. Retrying ..

**Comment by ajkl** [comment]
I see workers up in the latest cluster but still dont see them when I create the client.

```service "jupyter-notebook" created
service "dask-scheduler" created
replicationcontroller "jupyter-notebook" created
replicationcontroller "dask-scheduler" created
replicationcontroller "dask-worker" created
INFO: Waiting for kubernetes... (^C to stop)
INFO: Services are up
INFO: Pods are up
Addresses
---------
   Web Interface:  http://35.185.64.235:8787/status
Jupyter Notebook:  http://104.196.140.94:8888
     Jupyter Lab:  http://104.196.140.94:8889
Config directory:  /Users/ajkale/.dask/kubernetes/dask-cluster-5
 Config settings:  /Users/ajkale/.dask/kubernetes/dask-cluster-5.yaml

To connect to scheduler inside of cluster
-----------------------------------------
from dask.distributed import Client
c = Client('dask-scheduler:8786')

or from outside the cluster

c = Client('35.185.64.235:8786')

Live pods:
{u'dask-scheduler': [u'dask-scheduler-68wk3'], u'jupyter-notebook': [u'jupyter-notebook-45hld'], u'dask-worker': [u'dask-worker-1c58m', u'dask-worker-dmt9m', u'dask-worker-lnzkx', u'dask-worker-zhbm3']}
```


![](https://user-images.githubusercontent.com/4917183/28283239-08ef2d0e-6ae2-11e7-908d-9216fa8a2b5c.png)
<img width="721" alt="screen shot 2017-07-17 at 11 17 01 am" src="https://user-images.githubusercontent.com/4917183/28297515-39c67766-6b23-11e7-903f-e8d7dea0d1c5.png">

**Comment by martindurant** [comment]
Can you check that the worker pods are not just existant, but healthy? Something like
```
kubectl get pods
```
(in the terminal session that creates the cluster, you should be connected to the right kubernetes controller).

It is indeed worth getting logs of the workers to see what they are doing
```
kubectl logs dask-worker-zhbm3
```
(this is one of the IDs from your printout, above)

**Comment by martindurant** [comment]
https://github.com/dask/dask-kubernetes/pull/47 may have solved the issue for you - would you mind trying again with master?

**Comment by ajkl** [comment]
I just tried with the master. For some reason the worker creation doesnt go through. The worker pods are never healthy. I dont think thats a dask issue, I will report back if I figure that out.

**Comment by ajkl** [comment]
You were right that indeed was the problem. I should have chcked the worker logs before.
```
dask-kubernetes ajkale$ kubectl logs dask-worker-5fk1l
Usage: dask-worker [OPTIONS] [SCHEDULER]

Error: Invalid value for "--nthreads": 2.0 is not a valid integer
```

The #47 fix solved it. I could get it working with jupyter lab too. I see the workers in healthy state now. 

Unrelated, I got some JS errors with bokeh in jupyter-lab notebook - `Widget Javascript not detected.  It may not be installed or enabled properly.` but it works fine with jupyter notebook (without the jupyter-lab).

**Comment by martindurant** [comment]
OK, cool. 
The jlab/JS thing I don't really know about, sorry. jlab has been undergoing rapid development, so it could be a temporary situation.
