### ISSUE TITLE
Helm chart doesn't include any roles

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#479]
The helm chart for the operator that was added in #452 has a service account but no roles. This means the chart doesn't work out of the box. The chart has been published in the latest release (`2022.5.0`) and is available at https://helm.dask.org. But we don't currently document it.

@samdyzon do you have thoughts about how the operator installed via the chart will authenticate with the cluster? Should we add roles or did you have something else in mind?

It would also be good to document using the helm chart.

**Comment by samdyzon** [comment]
Looks like I've forgotten to add the service account roles to the helm chart - I totally thought I did that, sorry! To fix this, I can put together a PR which by default creates a service account which has the same roles and role bindings as the manifest in `dask_kubernetes/operator/deployment/manifests/operator.yaml` - if a user decides to override the `values.yaml` file to not create a serviceAccount by default, they will be required to provide their own roles/rolebindings.

**Comment by jacobtomlinson** [comment]
Closed in #480
