### ISSUE TITLE
Trouble installing the new operator

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask-kubernetes#518]
**What happened**:
I tried installing the new dask operator:
```powershell
> helm install dask-operator `
>>   dask/dask-kubernetes-operator `
>>   --version 2022.5.2 `
>>   --namespace dask
NAME: dask-operator
LAST DEPLOYED: Fri Jun  3 00:06:44 2022
NAMESPACE: dask
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Operator has been installed successfully.
```
...which *seemed* to work

```
> helm list -n dask
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
dask-operator   dask            1               2022-06-03 00:06:44.6074424 +1000 AEST  deployed        dask-kubernetes-operator-2022.5.2       2022.4.1
```
But the pod is in ImagePullBackOff:
```
> kubectl -n dask describe pod/dask-operator-dask-kubernetes-operator-64755dd787-j8qc2
<SNIP>
Containers:
  dask-kubernetes-operator:
    Container ID:
    Image:          ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4m4cm (ro)
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m23s                 default-scheduler  Successfully assigned dask/dask-operator-dask-kubernetes-operator-64755dd787-j8qc2 to aks-compute-23814378-vmss000001
  Normal   Pulling    112s (x4 over 3m23s)  kubelet            Pulling image "ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress"
  Warning  Failed     112s (x4 over 3m22s)  kubelet            Failed to pull image "ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress": failed to resolve reference "ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress": ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress: not found
  Warning  Failed     112s (x4 over 3m22s)  kubelet            Error: ErrImagePull
  Warning  Failed     98s (x6 over 3m22s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    85s (x7 over 3m22s)   kubelet            Back-off pulling image "ghcr.io/dask/dask-kubernetes-operator:set-by-chartpress"
```
..and seems to be trying to pull a version *`set-by-chartpress`*.

i.e. the version appears to not be being set by chartpress!

**Environment**:

- Dask version: latest
- Python version: py39
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by dhirschfeld** [comment]
> *as a workaround I recommend following the non-helm instructions*

As all our production deployments use helm I'm keen to help ensure that works. Passing the `image.tag` is an easy fix here but I'm currently blocked on #520.

It seems the permissions fix went in in #512 but it appears a release hasn't been made which incorporates that yet.

I probably won't have much time to look into it in the immediate future so I'm happy to wait for a release (or two). I just thought I'd kick the tyres to see how we could add the new operator to our workflow - I'm pretty excited about it's potential! :rocket:

**Comment by jacobtomlinson** [comment]
Thanks @consideRatio.

We don't use leading zeros here do shouldn't be a problem. The rest of Dask is also looking to drop them.

I'll look into the `valuesPath` thing and see if I can set that correctly.

**Comment by consideRatio** [comment]
Hmmm, I configured `valuesPath: image` in chartpress.yaml besides other image related config, and i got this.

![image](https://user-images.githubusercontent.com/3837114/172435164-b32f85ae-716f-4d5b-9607-999a61511aa5.png).

Removing `imageName` from the image config and adding `imagePrefix` to the chart config, i got the same output as well. Chartpress will update image.name to match its configuration atm. It will need to know how to name the image no matter what, and currently it doesn't read it from the values.yaml file but instead decides it based on configuration in chartpress.yaml.

If you want to change chartpress behavior, open a dedicated issue in the jupyterhub/chartpress repo as that merits clear motivation and discussion.

**Comment by jacobtomlinson** [comment]
@consideRatio ah I was setting it to `valuesPath: image.tag`. My mistake. Many thanks!
