### ISSUE TITLE
Insight into configuration options

### ISSUE THREAD

**Issue by ckemere** [dask/dask-kubernetes#52]
I've recently started exploring using dask-kubernetes to automate cluster deployment. Is it possible to add a few more comments to the defaults.yaml configuration file?

For example:
One of the first things I wanted to do is to see how things scale as I add more workers. There's a basic formula that I think I understand

count * cpus_per_worker + jupyter cpu + scheduler cpu <= num_nodes * cpus per node

But why is the cpus_per_worker non-integer? When I dig a bit further, the default value of 1.8 appears to get normalized to 2.

**Comment by martindurant** [comment]
Your assessment sounds about right. How does one add descriptions into YAML?

How kubernetes actually assigns containers to nodes is complicated, remembering that the kubernetes infrastructure also needs some resources of its own.

Specifically about cpus_per_worker, kuberetes does allow for fractional CPU assignments, which you will likely not notice unless using fairly large machines. Each dask worker will use an integer threads, so there should be slight over-subscription.

**Comment by mrocklin** [comment]
> How does one add descriptions into YAML?

https://stackoverflow.com/a/2276604/616616 ?
