### ISSUE TITLE
Cannot define additional containers using make_pod_spec and extra_pod_config

### ISSUE THREAD

**Issue by isaacbrodsky** [dask/dask-kubernetes#527]
Using make_pod_spec, it is not possible to add additional containers correctly.

```
In [43]: type(make_pod_spec('testimage').spec.containers[0])
Out[43]: kubernetes.client.models.v1_container.V1Container

In [44]: type(make_pod_spec('testimage', extra_pod_config={"containers":[{"name":"test"}]}).spec.containers[0])
Out[44]: dict

In [45]: type(make_pod_spec('testimage', extra_pod_config={"containers":[{"name":"test"}]}).spec.containers[1])
Out[45]: dict
```
Expected: type should be `kubernetes.client.models.v1_container.V1Container`

The type needs to be preserved because https://github.com/dask/dask-kubernetes/blob/f67c58b28e3af0a7126a40a2ceb675f1de6c6059/dask_kubernetes/objects.py#L207 requires that it be `V1Container`, not `dict`. Or, that line needs to be changed to accept `dict`.

Edit: Note: I tested on `2021.10.0`, apologies if this is not applicable to master, but it looks like it is.
Edit2: If you do work around this, then #320 applies.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Do you have interest in opening a PR to resolve this?

**Comment by isaacbrodsky** [comment]
Not immediately, I have a workaround where I modify the worker pod spec after calling this function.

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
