### ISSUE TITLE
Clean up pods

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#53]
I've noticed we're starting to accumulate a whole load of pods which are in the `Terminated: Completed` state.

Ideally these should be cleaned up in the same way JupyterHub cleans up pods after the user has logged off.

**Comment by mrocklin** [comment]
Ah, I didn't realize that this was necessary.  It imagine that there are
probably a few ways to do this:

   1. We could do it explicitly when we terminate the pod
   2. We could search for terminated pods when we start up new KubeClusters
   and close them.
   3. Perhaps there is some timeout we can put on pods in Kubernetes to
   have it take care of them?

**Comment by jacobtomlinson** [comment]
I have been experimenting with this further and it seems like workers only fail to clean up if I leave a cluster up and close my laptop for the night. When I return in the morning the notebook has been culled by JupyterHub and the workers have gone into `Completed` status.

I am failing to reproduce in any other way. I've tried:
- Unset the cluster variable
- Kill the notebook from the JupyterHub control panel
- Kill the notebook pod with `kubectl`
- Kill the notebook container with docker

**Comment by mrocklin** [comment]
Is there a way within Kubernetes to have it clean up completed pods after some time limit?

**Comment by jacobtomlinson** [comment]
I'm looking into it now. There seems to be lots of things for cleaning up pods created by `Jobs`. Things like `Deployments`, `DaemonSets` and `StatefulSets` clean up after themselves.

I think because creating pods manually is an unusual thing there are few tools around to help as the assumption is they will be managed by something else.

It might just be a case of writing something to run on the cluster which cleans these up.

**Comment by jacobtomlinson** [comment]
Potentially. However if I leave a cluster running and go on holiday for a week those pods will not be cleaned up until the next time I create a cluster.

I would prefer to install an agent on the cluster to manage overall cleanup. I expect this is what Jupyter Hub does although I need to look more into it.

**Comment by scottyhq** [comment]
just wanted to record that we were running into this at our demo using pangeo binder on aws today at the esip summer meeting (had 20 nodes running and 100+ workers for ~50 attendees). 

```
dask-scottyhq-pangeo-binder-test-93i745j1-fe63cbd0-94bp26       0/1     Completed   0          113m   192.168.8.122    ip-192-168-20-93.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-93i745j1-fe63cbd0-9vfdsf       0/1     Completed   0          113m   192.168.64.11    ip-192-168-91-24.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9e4mpnnx-49c82471-c8fnf8       0/1     Completed   0          113m   192.168.36.232   ip-192-168-47-75.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9e4mpnnx-49c82471-cw65dq       0/1     Completed   0          113m   192.168.0.13     ip-192-168-11-200.us-west-2.compute.internal   <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-58kpln       0/1     Completed   0          110m   192.168.63.231   ip-192-168-36-53.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-58mdxc       0/1     Completed   0          110m   192.168.58.180   ip-192-168-35-48.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-59lh4q       0/1     Completed   0          110m   192.168.12.17    ip-192-168-23-148.us-west-2.compute.internal   <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5fjqcl       0/1     Completed   0          110m   192.168.26.43    ip-192-168-20-93.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5jw6kr       0/1     Completed   0          110m   192.168.31.157   ip-192-168-19-35.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5mrlc7       0/1     Completed   0          110m   192.168.24.200   ip-192-168-2-191.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5q6cl6       0/1     Completed   0          110m   192.168.92.181   ip-192-168-76-26.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5q75dl       0/1     Completed   0          110m   192.168.22.141   ip-192-168-2-191.us-west-2.compute.internal    <none>
dask-scottyhq-pangeo-binder-test-9z0m3408-5a38460a-5rp8pz       0/1     Completed   0          110m   192.168.15.174   ip-192-168-30-211.us-west-2.compute.internal   <none>
```

**Comment by jacobtomlinson** [comment]
Thanks for the update! These do not have any negative effect in terms of cost or resources on your cluster, so don't worry about that. However I would like to resolve this at some point.

Short term: I expect these will be cleaned up the next time someone uses dask-kubernetes on your binder.

Long term: I'm keen to explore whether using the `Job` primitive rather than the `Pod` primitive would avoid this all together.

**Comment by jacobtomlinson** [comment]
I'm going to close this out now as completed pods are cleaned up when a new cluster is started. There isn't much we can do about fixing this when clusters are unexpectedly killed.
