### ISSUE TITLE
Get scheduler logs

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#54]
I'm having issues getting the adaptive functionality to work. There are tasks on the queue but no workers are being provisioned.

To troubleshoot this I would like to be able to see the logs for the scheduler but am unsure of how to access them.

**Comment by mrocklin** [comment]
There are a few ways:

```python
cluster = KubeCluster(silence_logs=False)  # see LocalCluster for explanation of keyword arguments
```

navigate to the info pages in the dashboard and then click on the logs button .  It's at info/main/logs.html

Call `client.get_scheduler_logs()`

**Comment by jacobtomlinson** [comment]
Awesome thanks!
