### ISSUE TITLE
Consolidate operator installation manifests

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#547]
Installing the operator means applying 4 manifests (5 with #451).

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1610850/186444157-051d7a7a-99a9-4966-9819-92df58ae4593.png">

_Source: https://kubernetes.dask.org/en/latest/operator_installation.html_

Given that we are [automatically building the CRDs from templates](https://github.com/dask/dask-kubernetes/blob/main/ci/pre-commit-crd.py) we could extend this to finally concatenate all of these manifests into a single manifest for installation.

This would involve a final step in that script that would concatenate all the manifests in `dask_kubernetes/operator/deployment/manifests` into one file separated with `---` lines.

This file would probably be called something like `dask_kubernetes/operator/deployment/manifests/all.yaml`

**Comment by jacobtomlinson** [comment]
It would also be nice to have some way of getting the path to the local manifests if you have `dask-kubernetes` installed.

Maybe this would be a good use for the new `dask` CLI. We could add a `kubernetes` namespace that does this.

```console
$ dask kubernetes get-operator-manifest
/Users/jtomlinson/miniconda3/envs/test-dask-kubernetes/lib/python3.10/site-packages/dask_kubernetes/operator/deployment/manifests/all.yaml
```

This way you could pass this straight into `kubectl` to ensure you're installing the same operator version as your locally installed package.

```console
$ kubectl apply -f $(dask kubernetes get-operator-manifest)
...
```

**Comment by patrik93** [comment]
Hi there, I would be happy to start on this issue. The first part is clear, however the comment added after would need some clarification since I'm not actively using the CLI tool. Is it an option to separate this two into 2 issues? 

Thanks!
