### ISSUE TITLE
Persistence with dask-kubernetes dashboard

### ISSUE THREAD

**Issue by caleb-recursion** [dask/dask-kubernetes#567]
Hi there, this might be a feature request or it might be a newbie question, thanks for any pointers.

I have a system that uses dask-kubernetes to run some distributed python workloads in ephemeral clusters. The dashboard is very useful but only lives as long as the k8s scheduler pod lives. Once the job finishes the dashboard is not accessible because the pod has been cleaned up. I would like to be able to access these metrics and job history for future analysis and persist it... anywhere. As far as I can see my options are:

1. Force the pod to stay alive after completion. From what I can understand this is an antipattern from k8s perspective.
2. Host the dashboard somewhere else and point the dask scheduler and workers to it. Not clear on how to do this but seems like the proper solution.
3. Stop using ephemeral clusters. The cluster per job workflow is nice but not required.

Thanks in advance.

**Comment by caleb-recursion** [comment]
Should I keep a persistent scheduler around and submit multiple jobs or tasks through it?

**Comment by jacobtomlinson** [comment]
I think you're looking for [performance reports](https://distributed.dask.org/en/stable/diagnosing-performance.html#performance-reports) which dump metrics to a static HTML file that you can view any time in the future after the cluster has been cleaned up.
