### ISSUE TITLE
Creating KubeCluster asynchronously does not start a cluster

### ISSUE THREAD

**Issue by john-jam** [dask/dask-kubernetes#598]
**Describe the issue**:

When creating the `operator.KubeCluster` with the `asynchronous` param to `True`, the cluster is never started.

In the example below, I got this error when I try to call the `adapt` method:
```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"daskclusters.kubernetes.dask.org \"dask-john-b1b26482-b\" not found","reason":"NotFound","details":{"name":"dask-john-b1b26482-b","group":"kubernetes.dask.org","kind":"daskclusters"},"code":404}
```

My guess is that the `_start` method of `operator.KubeCluster` is never called. With the `classic.KubeCluster`, when running asynchronously, the `_start` method was called in the `distributed.SpecCluster` class [here](https://github.com/dask/distributed/blob/main/distributed/deploy/spec.py#L395:L403). The new `operator.KubeCluster` inherits from `distributed.Cluster` instead and if I add the  `__await__(self):` it works and the cluster is created.

**Minimal Complete Verifiable Example**:

```python
import asyncio
from dask_kubernetes.operator.kubecluster.kubecluster import KubeCluster
from dask.distributed import Client
import time


def say_hello():
    print("hello from worker!")
    time.sleep(10)


async def try_cluster():
    cluster = await KubeCluster(
        image="ghcr.io/dask/dask",
        asynchronous=True,
    )
    await cluster.adapt(1, 1)

    client = Client(
        cluster, asynchronous=True
    )
    await client.submit(say_hello)
    await cluster.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    coroutine = try_cluster()
    loop.run_until_complete(coroutine)
```

**Anything else we need to know?**:

I opened a question on the Dask's forum [here](https://dask.discourse.group/t/new-operator-kubecluster-and-speccluster/1212) and this bug was found when trying to run the new `operator.KubeCluster` (as recommended by Dask's documentation) with prefect (opened issue [here](https://github.com/PrefectHQ/prefect-dask/issues/38)).

**Environment**:

- Dask version: 2022.10.2
- Python version: 3.8.13
- Operating System: Ubuntu 20.04.5 LTS
- Install method (conda, pip, source): pip

**Comment by john-jam** [comment]
> Would you be interested in raising a PR with this change?

Yes sure. I think I'll add it in the `KubeCluster` class if that works for you.

**Comment by jacobtomlinson** [comment]
Yup that makes sense.
