### ISSUE TITLE
Expose dashboard

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#6]
We should find a way to expose the dashboard externally.

**Comment by yuvipanda** [comment]
http://github.com/jupyterhub/nbserverproxy is probably the way to go, however it doesn't support websockets yet. It shouldn't be too hard to add websocket support to that proxy however...

**Comment by mrocklin** [comment]
In terms of the upcoming talks do you have a sense of if this is doable by monday?

**Comment by mrocklin** [comment]
https://github.com/yuvipanda/nbserverproxy/tree/websockets

**Comment by yuvipanda** [comment]
This was merged! \o/

**Comment by mrocklin** [comment]
OK, I *thought* that I had seen evidence of this working, but it appears not to be so.  Or more likely I'm not setting things up properly.  @yuvipanda if you find yourself near a computer sometime soon and feel like looking at this that would be welcome.  

I recommend installing `distributed` from master

    pip install git+https://github.com/dask/distributed --upgrade

And then running the following lines:

```python
from daskernetes import KubeCluster
cluster = KubeCluster(service_kwargs={'bokeh': {'prefix': 'user/yuvipanda/proxy/8787'}})
```

Verify that things passed through to Bokeh by checking the following:

```python
>>> cluster.scheduler.services['bokeh'].prefix
/user/yuvipanda/proxy/8787
>>> cluster.scheduler.services['bokeh'].port
8787
```

Then presumably navigate to http://pangeo.pydata.org/user/yuvipanda/proxy/8787 .  When I do this I don't get anything helpful.  I may not be doing this correctly though.

**Comment by yuvipanda** [comment]
Can you try it without the prefix and see if that works?

**Comment by yuvipanda** [comment]
I'll probably be around a computer tomorrow but unfortunately not today

**Comment by mrocklin** [comment]
No luck when omitting the prefix.  

> I'll probably be around a computer tomorrow but unfortunately not today

Works for me.  I appreciate your time on this.  Things are looking good now on the data access side.  We're starting to look usable now :)

**Comment by ogrisel** [comment]
Ok so this issue should be closed then?

For my own needs, I manually `kubectl port-forward dask-scheduler-pod-name 8787` which is enough for me but a bit too manual for the end users.

**Comment by mrocklin** [comment]
Yes, I think so.  We might improve documentation around this topic at some point, but from a technical perspective this seems to be resolved with nbserverproxy.

**Comment by timothy-mugayi** [comment]
Hi folks sorry to hijack this closed thread, thought this might be a useful place to ask the question if am running dask Kubernetes without using jupyterhub in a production pipeline, What would be the best way to tap or hook into and expose the ephemeral dask cluster via the dashboard UI whenever the scheduler is created at ad-hoc?

**Comment by jacobtomlinson** [comment]
@timothy-mugayi I've moved your comment into a new issue. Best not to comment on old closed issues.
