### ISSUE TITLE
Operator Helm chart needs updating - missing `daskworkergroups/scale` permission

### ISSUE THREAD

**Issue by timblakely** [dask/dask-kubernetes#604]
Looks like the current version (2022.10.1) of `dask-kubernetes-operator` on ArtifactHub is missing the `daskworkergroups/scale` permission that was added in #584:

![image](https://user-images.githubusercontent.com/11380482/200927915-25feedb4-e75e-46cc-9272-e7eefa3d8a56.png)

This prevents the operator from scaling workers unless you manually patch in the permission. With default Helm values this is problematic to automate by the fact that the operator RBAC and service account are auto-generated with a timestamp, so the permission must be manually updated.

I think this only requires a new push to Helm to rectify...?

**Comment by jacobtomlinson** [comment]
Yup this has already been fixed. I'll get a release out soon.
