### ISSUE TITLE
wild adapt

### ISSUE THREAD

**Issue by timkock** [dask/dask-kubernetes#62]
Hey guys, we love this, integrated it with Azure, kubernetes and node autoscaling. It's very cool. We tried the `adapt` method too which was hilarious as it maxed out our Azure quota by spawning 1000+ workers and getting the autoscaler very excited. 

I was wondering, would an `adapt_withinreason` be welcome or a pull request to add some parameters to the `adapt` method?

In any case, epic work

**Comment by mrocklin** [comment]
You probably want this, which is implemented today:

    cluster.adapt(maximum=100)

**Comment by mrocklin** [comment]
We should improve documentation for adaptive scheduling.

**Comment by jacobtomlinson** [comment]
Good stuff! This is a good example of why adding the min and max to the adaptive scheduler was a good thing.

**Comment by timkock** [comment]
Works very well, we are testing this and it does the job. We are now running into an edge case where computation is done but communication with worker is still required but adapt kills them. So we are digging into conditions where adapt is allowed ahead and what it needs to check for.

**Comment by jacobtomlinson** [comment]
Out of curiosity what situation requires you to communicate with them?

**Comment by limx0** [comment]
> Works very well, we are testing this and it does the job. We are now running into an edge case where computation is done but communication with worker is still required but adapt kills them. So we are digging into conditions where adapt is allowed ahead and what it needs to check for.

+1 also seeing this behaviour
