### ISSUE TITLE
Add `--nworkers` to `dask_kubernetes.common.objects.make_pod_spec`

### ISSUE THREAD

**Issue by henrifroese** [dask/dask-kubernetes#652]
The `dask-worker` CLI has argument `--nworkers` that specifies the number of processes the worker should run with (See https://docs.dask.org/en/latest/deploying-cli.html#dask-worker and https://distributed.dask.org/en/stable/worker.html#thread-pool). I wanted to run something CPU-bound in Python (doesn't release the GIL) using Dask Kubernetes. Currently, if you e.g. want to fully use 1000 vCPUs with this, you'd have to create 1000 workers each with 1 process. Would be great to have an `nworkers` argument (probably want to name it something different, maybe `processes_per_worker` similar to the `threads_per_worker` argument) to give users more flexibility here.

I added it by just doing `pod_template.spec.containers[0].args.extend(["--nworkers", str(n_workers)])` and it worked fine.

Happy to submit a PR if this feature makes sense.

**Comment by jacobtomlinson** [comment]
I totally see how you would want to configure something like this. But I often find there is a balance to be struck between adding useful kwargs and making things overwhelmingly configurable.

I also note you're talking about the classic implementation of `KubeCluster` which is currently in maintenance mode and will be removed in a future version. In the new implementation of `KubeCluster` we've tried to balance this by keeping the kwargs minimal and making it [more pleasant for folks to dig under the hood](https://kubernetes.dask.org/en/latest/operator_kubecluster.html#customising-your-cluster) as you have. 

So I'm afraid I don't think we would accept a PR to add this to the classic `KubeCluster` at this point. If you have code that works today for your use case by tweaking the pod template after it has been generated then that's great. But I would suggest you look at migrating to the new implementation.

**Comment by henrifroese** [comment]
Makes sense, thanks! Migrating is definitely on the radar, but we're very heavy Dask users and the codebase is quite coupled to the current implementation, so that'll take some time.
