### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'get'")

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/dask-kubernetes#66]
I am running a Pangeo-like deployment on gke. I am attempting to use an adaptive cluster to spin up many workers to ping a url on a NASA server, download data to local store then save to a google store using gcsfs. I can use dask with the local cluster and it works wonderfully. When I try to use KubeCluster I get the error:

`AttributeError("'NoneType' object has no attribute 'get'")` 

My worker and scheduler pass the `check_versions=True` test. 

Is there anything obvious about that I am missing?

**Comment by mrocklin** [comment]
I recommend including the code, exception, and traceback in your report.
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports,
particularly the section "Provide complete tracebacks"

**Comment by jgerardsimcock** [comment]
For us this issue was based in permissions/credentials for workers and gce.  We have solved this.

**Comment by BrendanMartin** [comment]
@jgerardsimcock how did you fix this? I'm getting this error right now
