### ISSUE TITLE
`ResourceQuota` handling

### ISSUE THREAD

**Issue by bstadlbauer** [dask/dask-kubernetes#684]
**Describe the issue**:
Whist running the operator in production, we've recently noticed that sometimes a `DaskJob` is stuck in the `"JobCreated"` state. Upon further inspection, we've seen that the operator is not able to schedule one of the pods in most cases. The reason behind this is that we've got namespace-wise `ResourceQuota`s in place, which are then used up by the worker pods, leaving no space for the runner pod to launch. 

We're seeing an error similar to the following one:

```
kubernetes_asyncio.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: <CIMultiDictProxy('Audit-Id': '38a12602-5719-4d7e-bb02-325bd12dd85e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ec346534-3e72-417d-88b8-de9cd45795e0', 'X-Kubernetes-Pf-Prioritylevel-Uid': '6ee0e2ec-80ac-421f-a6ff-dae05057166a', 'Date': 'Thu, 23 Mar 2023 09:41:49 GMT', 'Content-Length': '417')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"simple-job-default-worker-8fd7f483ae\" is forbidden: exceeded quota: default-quota, requested: requests.cpu=500m,requests.memory=500Mi, used: requests.cpu=1,requests.memory=1000Mi, limited: requests.cpu=1,requests.memory=1Gi","reason":"Forbidden","details":{"name":"simple-job-default-worker-8fd7f483ae","kind":"pods"},"code":403}
```

@jacobtomlinson I am happy to fix this, but I am not quite sure what the best strategy is here or what general k8s best practices are when dealing with restricted resources. I am also not sure about the internals of `kopf` (i.e. how often it retries), because if it would retry indefinitely, the `job` should start running eventually? Two concerns that I have: 
1. If we "just" retry, a large cluster might be up, idling, just waiting for the `job-runner` to come up
2. In case the scheduler does not come up in time, we might run into timeout issues (we've already increased our overall timeout to ~10 minutes to deal with node cold start, etc.)

**Minimal Complete Verifiable Example**:
I've added a resource quota to the `test_job` test in https://github.com/dask/dask-kubernetes/pull/683 which should replicate the issue. Note that the test does not fail (even though it probably should)

**Environment**:

- Dask version: 2023.1.1 (operator)
- Python version: 3.8.16 (operator)
- Operating System: linux
- Install method (conda, pip, source): helm

**Comment by jacobtomlinson** [comment]
Thanks for raising this. A few thoughts:
- We definitely need to add a failing test for this.
- If the kopf handler is raising an exception then kopf will retry, so I wouldn't expect us to need to handle the retry ourselves. 
  - We should verify this is the case. 
  - We might need to catch the exception and reraise something else.
- A solution might be to create two `PriorityClass` objects, one for the scheduler and job pod and a lower priority one for the workers. 
  - I'm not sure if that's in scope for dask-kubernetes or whether it's something we should document for users to do. 
  - You would still get stuck if the job code needs to wait for all workers.

**Comment by Artimi** [comment]
We've also encountered this issue. For dask job, scheduler and workers we are able to specify it in the deployment specification.
However, for dask kubernetes operator it is hard to set because it is missing in possible values https://github.com/dask/dask-kubernetes/tree/main/dask_kubernetes/operator/deployment/helm#configuration. We use the helm as dependency so only way how to update it is through dependency. Would it be possible to add something like

```
{{- with .Values.priorityClassName }}
priorityClassName: {{ . | quote }}
{{- end }}
```
to the operator deployment? https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml#L21 I can open PR if you agree.

**Comment by bstadlbauer** [comment]
@jacobtomlinson Quick update from my end here - we've also gone down the road of using priority classes here. 

As we're using Flyte do create our cluster we don't have an immediate way to set the `PriorityClass` of the components (as least not yet). We've ended up using a mutating admission webhook to adjust the `DaskJob` resource accordingly. 

Happy to close this from my end
