### ISSUE TITLE
Improve logging during fail cases

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#7]
Currently we fail silently when launching pods fail.  We might consider waiting for the pods to finish before leaving `scale_up`.  This would require an asynchronous solution.

Logging generally could probably be improved.

**Comment by jacobtomlinson** [comment]
The classic `KubeCluster` was removed in https://github.com/dask/dask-kubernetes/pull/890. All users will need to [migrate to the Dask Operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html). Closing.
