### ISSUE TITLE
Ideal user documentation flow

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#703]
Where do we want users to go when looking at docs?  Right now kubernetes.dask.org points to docs.dask.org, which lists the helm chart as a first choice.  My sense is that the Kubernetes operator is stronger today.  Is my understanding correct?  If so it seems like this user flow is suboptimal, and that we should point people to kubernetes.dask.org and it should keep them here.

Thoughts?   @jacobtomlinson ?

**Comment by jacobtomlinson** [comment]
Yeah totally, this has also been on my mind recently. I've been working on [a comparison table](https://docs.google.com/spreadsheets/d/169t2B7MqUpoWyMsrwPV_TXxP8jcQuK9SCgH-Vhqr240/edit#gid=0) of the four ways of deploying Dask on Kubernetes (Helm, KubeCluster classic, Operator and Gateway).

Ideally, I want the default to be the operator for the majority of users. Folks with special cases that require a gateway should also consider that. Classic is deprecated and scheduled to be removed by the end of the summer. The single-user helm chart is still valid and useful, but I'd like to update it to build on the operator which would address most of its shortcomings.

Given our proliferation of Kubernetes tooling, I still think the docs.dask.org page is a good catchall page to signpost folks to the right place for them. But that page needs updating with the comparison table I've been working on and needs reordering to use the operator first and then discuss reasons why you might want the other tools.

**Comment by mrocklin** [comment]
I'm talking to lots of folks from conferences right now and when they're married to Kubernetes I'm sending them to kubernetes.dask.org.  Is that where you'd like me to send them today?   Are there things we can do to make that a better landing experience now while we wait for other things to settle?

**Comment by jacobtomlinson** [comment]
That's a fine place to send them. As you say the note will redirect new users to docs.dask.org.

I've opened https://github.com/dask/dask/pull/10232 to update the docs page with up-to-date information about Dask Kubernetes, Dask Gateway and the Helm Charts.

**Comment by jacobtomlinson** [comment]
I'm going to close this issue now that https://github.com/dask/dask/pull/10232 is merged. But finishing up the comparison table and further improving the docs and writing a blog post are on my todo list.
