### ISSUE TITLE
KubeCluster on Windows raises  error: _WindowsSelectorEventLoop does NOT support subprocesses

### ISSUE THREAD

**Issue by elleryames** [dask/dask-kubernetes#709]
**Describe the issue**:
Attempting to instantiate a `KubeCluster` on a Windows machine leads to a runtime error. After installing dask-kubernetes (in my case via conda) and running the minimal example below, I get the error 
> ERROR:root:exec: _WindowsSelectorEventLoop does NOT support subprocesses, see README.md

followed by a traceback concluding in 

> kubernetes_asyncio.client.exceptions.ApiException: (403)
> HTTP response body: {“kind”:“Status”,“apiVersion”:“v1”,“metadata”:{},“status”:“Failure”,“message”:“[daskclusters.kubernetes.dask.org](http://daskclusters.kubernetes.dask.org/) is forbidden: User "system:anonymous" cannot create resource "daskclusters" in API group "[kubernetes.dask.org](http://kubernetes.dask.org/)" in the namespace "[MY_NAMESPACE]"”,“reason”:“Forbidden”,“details”:{“group”:“kubernetes.dask.org”,“kind”:“daskclusters”},“code”:403}

**Minimal Complete Verifiable Example**:

```python
from dask_kubernetes.operator import KubeCluster
cluster = KubeCluster(name='foo', namespace='bar') # RuntimeError
```

**Anything else we need to know?**:
The error appears to be coming from the `kubernetes_asyncio` library, which has an [explicit warning](https://github.com/tomplus/kubernetes_asyncio#microsoft-windows) about the WindowsEventLoop. Executing the suggested work-around at the above link before instantiating a `KubeCluster` does not change the error message.

I have tested this example against multiple versions of dask/dask-kubernetes (from v2022.12.0), and python versions 3.9.16 and 3.10.11.

A related discussion was started on the [dask.discourse](https://dask.discourse.group/t/eventloops-and-kubecluster-on-windows/1831)

**Environment**:

- Dask version: 2023.3.2
- Python version: 3.10.11
- Operating System: Windows
- Install method (conda, pip, source): conda

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

We do not currently run Windows in our CI to support is generally on a best-efforts basis.

We are also looking at replacing `kubernetes_asyncio` with `kr8s` in the near future so I expect this issue will get worked around.

**Comment by jacobtomlinson** [comment]
If you have any interest in running the `kr8s` test suite on Windows and report any issues there that would help us be confident that migrating will resolve this issue.

**Comment by jacobtomlinson** [comment]
We no longer use `kubernets_asyncio` so this problem may have been resolved. Given the lack of activity here I'm going to close this out. But if anyone experiences this problem in the future please comment here and I'll reopen.
