### ISSUE TITLE
KubeCluster.shutdown_on_close defaults to True

### ISSUE THREAD

**Issue by bnaul** [dask/dask-kubernetes#725]
**Describe the issue**:
The [docstring](https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/kubecluster/kubecluster.py#L102-L104) says 
```
    shutdown_on_close: bool (optional)
        Whether or not to delete the cluster resource when this object is closed.
        Defaults to ``True`` when creating a cluster and ``False`` when connecting to an existing one.
```
which is the behavior I'd expect. But in practice it's just `True` even for an existing cluster, which means when you close your interpreter/notebook kernel you kill your cluster (found this out the hard way!).

**Minimal Complete Verifiable Example**:
# Created a cluster `brett` w/ `kubectl`
<img width="770" alt="image" src="https://github.com/dask/dask-kubernetes/assets/903655/42c35a00-1b20-46cb-860d-c612958ad128">

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

We should add `shutdown_on_close=False` here

https://github.com/dask/dask-kubernetes/blob/6f7e45bbfa2e0b8db53d67455f0d095141a08fc3/dask_kubernetes/operator/kubecluster/kubecluster.py#L870
