### ISSUE TITLE
Workers remain idle and not cleaned up after terminating cluster or failure of dask job

### ISSUE THREAD

**Issue by mamoustafa** [dask/dask-kubernetes#737]
**Describe the issue**:

After terminating a cluster or failure of a cluster or even sometime successful completion of a dask job, the workers remain idle and are not cleaned up. Expected behavior is that after a job completes successfully or unsuccessfully, the workers should be cleaned up automatically.

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
cluster = KubeCluster(spec)
cluster.scale(n_workers)
client = Client(cluster)
# Run some load here
# Terminate the cluster while running and you will find that the worker nodes are not cleaned up and requires manual deletion.
```
**Environment**:

- Dask version: 2023.3.0
- Python version: 3.8
- Operating System: 
- Install method (conda, pip, source):

**Comment by jacobtomlinson** [comment]
This is a known problem with the way the classic `KubeCluster` is implemented. One of our goals with the new implementation is to resolve problems like this using custom resources and good resource ownership practices.

Given that the classic `KubeCluster` implementation is going to be removed in the future I recommend that you [migrate to the operator](https://kubernetes.dask.org/en/latest/kubecluster_migrating.html).
