### ISSUE TITLE
Run Dask Operator container as non-root

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-kubernetes#776]
Many clusters prohibit running containers as root to optimize security. The Dask operator container runs as root. Any particular reason why? Would creating and switching to user 1000 break the application code in any way?

**Comment by jacobtomlinson** [comment]
No reason at all. I think we would just need to tweak the `Dockerfile` and `deployment.yaml` to make this the default.

**Comment by jsonmp-k8** [comment]
The deployment has the option to pass runasuser param in the values file. The Dockerfile needs to be adjusted to make sure the image has the right user.

**Comment by droctothorpe** [comment]
Closed by https://github.com/dask/dask-kubernetes/pull/777.
