### ISSUE TITLE
Regarding dask/dask#10499

### ISSUE THREAD

**Issue by BitTheByte** [dask/dask-kubernetes#816]
https://github.com/dask/dask/pull/10499 breaks this repository

**Comment by jrbourbeau** [comment]
I believe this was closed by https://github.com/dask/dask/pull/10499

**Comment by jacobtomlinson** [comment]
@jrbourbeau I'm a little confused, you references the same PR that has been reported to break the repo?

**Comment by jacobtomlinson** [comment]
Awesome thanks @jrbourbeau
