### ISSUE TITLE
Configurable rich console

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-kubernetes#835]
The rich console generated by https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/kubecluster/kubecluster.py tends to be quite verbose. It might be helpful if `KubeCluster` included params that let you (1) disable the logs, or (2) clear them if the cluster deploys without issue, or (3) automatically collapse the output once the cell completes execution if there are no errors. Happy to implement if this sounds reasonable.

**Comment by jacobtomlinson** [comment]
You can disable them with `quiet=True`. Is that what you mean?

```python
from dask_kubernetes.operator import KubeCluster

cluster = KubeCluster(name="foo", quiet=True)
```

**Comment by jacobtomlinson** [comment]
> Does it make sense to also include it in the KubeCluster docstring / params for easier discovery?

Absolutely. Do you have any interest in opening a PR to add it to the docstring?

> It doesn't seem to work, even when I explicitly pass

That is strange. We explicitly check for it. I wonder if it is being overridden somewhere. Would you mind investigating?

https://github.com/dask/dask-kubernetes/blob/fa7255b95e686025fd818f718b83635ff9424769/dask_kubernetes/operator/kubecluster/kubecluster.py#L295-L296

**Comment by droctothorpe** [comment]
Will do 👍

**Comment by droctothorpe** [comment]
Having a hard time tracking this one down. Just to clarify, I'm not referring to the rich widget that looks like this:

![](https://i.imgur.com/k4JGk0n.png)

I'm referring to the wall of logs under it that as far as I can tell are being streamed from the controller. Not seeing where that's happening in KubeCluster so thought it might be handled by the cluster_manager in distributed/cluster but no dice. Then I thought maybe it's because kr8s/Pod.log is being called somewhere, but not sure.  If you any pointers, it would be greatly appreciated. Thanks!

**Comment by droctothorpe** [comment]
There are similar logs (though less of them), when `cluster.close()` is called.

**Comment by droctothorpe** [comment]
Have narrowed it down to something in [_create_cluster](https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/kubecluster/kubecluster.py#L331). Still digging.

**Comment by droctothorpe** [comment]
[cluster.exists](https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/kubecluster/kubecluster.py#L298) also logs out in a way that ignores `quiet`.

**Comment by droctothorpe** [comment]
I think it's this logic in the httpx library:

```python
        logger.info(
            'HTTP Request: %s %s "%s %d %s"',
            request.method,
            request.url,
            response.http_version,
            response.status_code,
            response.reason_phrase,
        )
```

**Comment by jacobtomlinson** [comment]
Thanks for digging, this makes a lot more sense. I haven't seen this behaviour myself but I would say this is totally independent of `dask-kubernetes`. It's just a consequence of using `httpx` under the hood in `kr8s`, it appears that `httpx` logs noisily.

Do you have some extra logging config somewhere that is setting the level to `INFO`? I would assume the default log level is `WARN`.

**Comment by droctothorpe** [comment]
I'll still submit a PR that adds the quiet param.
