### ISSUE TITLE
Dask dashboard not loading

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-kubernetes#839]
**Describe the issue**:
When I launch a Dask cluster using `operator.KubeCluster` within a Kubeflow-provisioned notebook, the resulting dashboard's navbar loads but none of the actual page content loads.

I followed the docs [here](https://github.com/dask/dask-kubernetes/blob/fa7255b95e686025fd818f718b83635ff9424769/doc/source/operator_installation.rst#dashboard-access), it didn't help.

The Chrome console reports the following errors:
<img width="1239" alt="image" src="https://github.com/dask/dask-kubernetes/assets/24783969/0e2edee6-c246-4606-b450-bf9f599753d8">

The javascript files look like this:

```javascript
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,user-scalable=yes"><meta name="description" content="Kubeflow Central Dashboard"><meta name="theme-color" content="#3f51b5"><title>Kubeflow Central Dashboard</title><link rel="shortcut icon" href="/assets/favicon.ico"><link rel="icon" href="/assets/favicon-32x32.png" sizes="32x32"><link rel="icon" href="/assets/favicon-57x57.png" sizes="57x57"><link rel="icon" href="/assets/favicon-76x76.png" sizes="76x76"><link rel="icon" href="/assets/favicon-96x96.png" sizes="96x96"><link rel="icon" href="/assets/favicon-128x128.png" sizes="128x128"><link rel="icon" href="/assets/favicon-192x192.png" sizes="192x192"><link rel="apple-touch-icon" href="/assets/favicon-152x152.png" sizes="152x152"><link rel="apple-touch-icon" href="/assets/favicon-180x180.png" sizes="180x180"><base href="/"><script src="webcomponentsjs/webcomponents-loader.js"></script><script src="webcomponentsjs/custom-elements-es5-adapter.js"></script><link href="app.css" rel="stylesheet"></head><body><main-page></main-page><noscript>Please enable JavaScript to view this website.</noscript><script src="vendor.bundle.js" defer="defer"></script><script src="app.bundle.js" defer="defer"></script><script src="dashboard_lib.bundle.js" defer="defer"></script></body></html>
```

Note this part:

> Please enable JavaScript to view this website.

**Anything else we need to know?**:
Betting it's jupyter-server-proxy related, but not seeing anything relevant issues here or there.

**Environment**:
- Dask version: 2023.10.0
- Python version: 3.9
- Operating System: OSX
- Install method (conda, pip, source): conda and pip

**Comment by jrbourbeau** [comment]
@droctothorpe what version of `bokeh` are you using?

**Comment by droctothorpe** [comment]
`3.3.0`

**Comment by jacobtomlinson** [comment]
Can you look at the network tab and see if there are any files failing to load in. I expect Bokeh is failing to load.

**Comment by droctothorpe** [comment]
Downgrading bokeh to 2.4.3 which is 1 patch version above what dask [specifies](https://github.com/dask/dask/blob/main/pyproject.toml#L61) appears to have resolved the problem! Thanks for the suggestion @jrbourbeau!
