### ISSUE TITLE
Add ability to explictly specify Kubernetes cluster

### ISSUE THREAD

**Issue by chrish42** [dask/dask-kubernetes#85]
Currently, `KubeCluster()` is hardcoded to launch Dask workers in the "current" Kubernetes cluster, this being either the cluster where the current process is running ("in-cluster config") or as a fall-back the default cluster in the kubeconfig file. As this may not be the right strategy for all use cases, it would be nice to be able to be able to optionally specify more explicitly which cluster to use. Here are the choices I currently see possible:

- in-cluster
- default from kubeconfig
- non-default cluster (other context) from kubeconfig
- other cluster (URL to Kubernetes API server + TLS certificate for connection... is anything else needed?)

**Comment by jacobtomlinson** [comment]
Definitely agree! We should be able to add some config options which would affect the kubernetes config load [here](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/core.py#L179).

**Comment by chrish42** [comment]
Yes. I'd see dask-kubernetes expose the following constants / data classes (names subject to tweaking):
- `IN_CLUSTER`
- `KubeConfig(config_filename=None, context=None)` # possible to override the location of the kubeconfig file used
- `KubeAuth(url=..., cert=..., other=..., details=...)` # with enough info to fill in a `kubernetes.client.Configuration` object.

People could then pass one of these (or a list) to dask_kubernetes.KubeCluster`. For example, `KubeCluster(auth=[IN_CLUSTER, KubeConfig()], ...)` would be like the current behavior (which we also probably want to be the default, so as not to break things). And `KubeCluster(auth=KubeAuth(url=..., cert=..., ...) would be what I would like to use in the future when the scheduler can run on the Kubernetes cluster too, so people don't need to install kubectl and/or gcloud...

What do you think?

**Comment by chrish42** [comment]
It's just not clear to me presently what fields are required in the `kubernetes.client.Configuration` object (https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L41)...

**Comment by jacobtomlinson** [comment]
Yeah that's one of the downsides of swagger generated SDKs. They can be a bit hard to follow.
