### ISSUE TITLE
Update dask-kubernetes to a newer kr8s

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#853]
Recently we unpinned `kr8s` but things broke, so the pin was set back to `0.9.0`. We need to manually update the pin to something more recent (and in theory more stable) before unpinning again.

**Comment by dbalabka** [comment]
@jacobtomlinson , could you please specify what exactly has been broken? Is it related to #848, or are there any other tickets?

**Comment by jacobtomlinson** [comment]
@dbalabka I think `box` was the biggest change, but there was also a lot of shifting around in the port-forwarding code so we may need to do some more testing there.

**Comment by dbalabka** [comment]
@jacobtomlinson , I noticed the changes in the port forwarding. As far I understood, dask-kubernetes uses a new way to forward ports. I tested it and it fixes the problem with websockets for us. Therefore, we don't need to use NodePort any more.

**Comment by dbalabka** [comment]
@jacobtomlinson I will perform more tests and give a feedback in https://github.com/dask/dask-kubernetes/issues/805
