### ISSUE TITLE
Scaling up only works initially 

### ISSUE THREAD

**Issue by fbergroth** [dask/dask-kubernetes#90]
I'm trying to do some batch jobs using dask-kubernetes. Initially i run:
```
cluster.adapt(minimum=1, maximum=6)
```

Which works fine, and I soon have 6 worker-pods running.

However, when a pod dies, another one isn't recreated, instead I get flooded with these messages (about every second):
```
2018-08-03 08:24:50 [INFO] distributed.deploy.adaptive: CPU limit exceeded [132485 occupancy / 5 cores]
2018-08-03 08:24:50 [INFO] distributed.deploy.adaptive: Scaling up to 6 workers
```
Any idea what's going on?

**Comment by jacobtomlinson** [comment]
Interesting! When a worker dies for me I tend to get a `KilledWorker` error and the whole thing exits.

Are you able to provide some example code so I could have a go at reproducing this?

**Comment by fbergroth** [comment]
Previously I just used `scale_up(6)`, and also saw `KilledWorker`, the future errored, but I could continue executing.

This time my worker pod got evicted, and dask-kubernetes fails to replace it.

I'm not quite sure how to reproduce it, I might have some time next week, but any help would be appreciated.

**Comment by fbergroth** [comment]
Okay, so it seems that the cluster doesn't have enough resources to spawn another pod. It should be checked in `scale_up` I guess, and the following note seems related to this as well:

https://github.com/dask/dask-kubernetes/blob/e8e919aa60f267ceb3986bd019d598730bd1a8cd/dask_kubernetes/core.py#L444

**Comment by fbergroth** [comment]
I think I found the issue, see #91
