### ISSUE TITLE
Incorrect example code snippet in the Autoscalers section of the docs index page

### ISSUE THREAD

**Issue by marcelovilla** [dask/dask-kubernetes#904]
**Describe the issue**:

In the [Autoscalers section of the docs index page](https://kubernetes.dask.org/en/latest/#autoscalers), there's an incorrect example code snippet on how to create a `KubeCluster` and scale it. Here is screenshot:

![image](https://github.com/user-attachments/assets/f9eed5e6-227c-4889-9164-88aa500f45d6)

Initially, I thought it was a duplicate snippet but @jacobtomlinson has [pointed out it's actually an incorrect example and it should depict how to adapt a cluster to use the autoscaler](https://github.com/dask/dask-kubernetes/pull/905#pullrequestreview-2276582837).

**Comment by jacobtomlinson** [comment]
Thanks! The example isn't a duplicate, but it is broken. See my comment on your PR https://github.com/dask/dask-kubernetes/pull/905#pullrequestreview-2276582837

**Comment by marcelovilla** [comment]
@jacobtomlinson ah, I see! That makes sense. Let me update the issue title and description to better convey this.
