### ISSUE TITLE
Default helm liveness probe timeout (1s) is too short

### ISSUE THREAD

**Issue by bnaul** [dask/dask-kubernetes#917]
After running `helm install --repo https://helm.dask.org dask-kubernetes-operator dask-kubernetes-operator --create-namespace -n dask-operator`, my `dask-operator` pod is continually being restarted due to failing the liveness probe: it seems like in practice it takes between 1 and 2s to respond. Patching the deployment and overriding the timeout to 5s resolved the issue.

Maybe the probe timeout could be made configurable in the helm template?

**Comment by jacobtomlinson** [comment]
Making that configurable would be great.
