### ISSUE TITLE
Running a single dask-scheduler-style process but with dask-kubernetes?

### ISSUE THREAD

**Issue by mturok** [dask/dask-kubernetes#94]
Is there a standard way to run a kubernetes based scheduler from a python process that will run as a daemon, much like the command-line dask-scheduler process?

**Comment by mrocklin** [comment]
Currently the answer to this question is "no" but it's a reasonable
request.  I recommend leaving this issue open.

**Comment by mturok** [comment]
I thought to leave this closed, b/c I think this is a duplicate of this:  https://github.com/dask/dask-kubernetes/issues/84

**Comment by jacobtomlinson** [comment]
It sounds like there are two things here that are interesting:

- Can we launch a `KubeCluster` using the CLI? Currently no but we could definitely add that.
- Can we detach from a running `KubeCluster` without it being cleaned up? Also no but is of interest.
