### ISSUE TITLE
Minikube SSL error “No such file or directory” during connection to the cluster using dask-kubernetes

### ISSUE THREAD

**Issue by VMois** [dask/dask-kubernetes#97]
I have a problem with running dask-kubernetes on minikube cluster. More info here:
- https://stackoverflow.com/questions/52191700/kubernetes-minikube-ssl-error-no-such-file-or-directory-during-connection-to-t

It's related to SSL, but I don't understand why kubernetes-python client works, but dask-kubernetes not. Maybe, you will have an idea how to solve it.

Thank you very much!

**Comment by tsuberim** [comment]
@VMois Hi, I'm getting a similar error, did you manage to solve it?
