### ISSUE TITLE
Deployment instead of single pods

### ISSUE THREAD

**Issue by mamoit** [dask/dask-kubernetes#99]
Pods are the current way of dask-kubernetes to define a worker.
They are very easy to spawn and kill, but they are not managed when it comes to kubernetes.

Since there is nothing controlling them in the *k8s* layer:
* the pods cannot be rescheduled in the case a node dies.
* the pods cannot be moved by the cluster autoscaler to scale down a node.

I sometimes find myself with half a dozen huge nodes, each running one or two small dask workers, wasting a lot of resources. If they could be rescheduled to other nodes, even if that meant re-starting a task, it would be a good trade-off.

It could of course be possible to avoid a worker from being rescheduled by the autoscaler by annotating the workers with `cluster-autoscaler.kubernetes.io/safe-to-evict = false`.

I'd like to put to consideration changing the worker scheduling method from single pods to a *deployment* or a simple *replication controller*.
This would give us the ability to scale up and down by setting the number of replicas.

On the downside, I think it would make it difficult to scale down a single worker, since there is no way (that I'm aware of at least), to tell which node to scale down on size change of either a replication controller or a deployment.

Ideas and insights needed :slightly_smiling_face:

**Comment by mrocklin** [comment]
We considered this when desigining dask-kubernetes.  It was important to us
to be able to pick which workers to scale down so that we could move data
around before that happened, and remove idle workers during adaptive
workloads.  Deployments didn't offer this ability.

**Comment by jacobtomlinson** [comment]
To echo what Matt says. In my initial version of this functionality I was using Deployments and found that occasionally the wrong worker would be removed.

When a worker is finished it exits. If the worker is managed by a Deployment then it will be recreated on exit. The adaptive class would reduce the size of the deployment at the same time as instructing the worker to exit, which should cause it to not be recreated. But this was victim to race conditions and occasionally the worker would be recreated before the deployment reduced, but then on reduction a different worker would be killed.

**Comment by mamoit** [comment]
I suspected that you must have already thought about it, and so you did.
Thanks for the insight :bowing_man:
